<a href="https://colab.research.google.com/github/UKD1211/Macroeconomic_impact_of_gold-_Econ_growth/blob/main/concated_dataset_forecast.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [49]:
import pandas as pd
import numpy as np

In [50]:
main_df = pd.read_excel("/content/Master_Dataset.xlsx")

In [51]:
main_df

,Date,Gold_Reservs_USD_mn,Gold_Volume_mn_troy_oz,Gold_Price[/10gm],Gold_CPI,USDINR,Repo_Rate,Overall_CPI,Inflation_YoY,Inflation_MoM,FPI_Net_INR_Crore,"GDP, current prices (Billions of U.S. dollars)","GDP per capita, current prices\n (U.S. dollars per capita)",Real GDP growth (Annual percent change),Remittances received (Personal remittances received current U.S. $)
0,2000-01,2945.0,11.502339,4510.75,---,43.59,---,---,---,---,196.5,468.396,442.751,3.8,12883465957.0616
1,2000-02,3104.0,11.502339,4712.25,---,43.65,---,---,---,---,3084.2,468.396,442.751,3.8,12883465957.0616
2,2000-03,2974.0,11.502339,4541.90,---,43.64,---,---,---,---,1198.9,468.396,442.751,3.8,12883465957.0616
3,2000-04,2895.0,11.502339,4462.06,---,43.68,---,---,---,---,2586.7,468.396,442.751,3.8,12883465957.0616
4,2000-05,2851.0,11.502339,4371.14,---,44.08,---,---,---,---,252.9,468.396,442.751,3.8,12883465957.0616
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
310,2025-11,106740.0,28.298487,122834.00,408.4,88.84,5.5,197.9,0.71,0.3,2836.0,3916.312,2675.322,7.6,---
311,2025-12,111262.0,28.303688,131322.55,433.9,90.04,5.25,198,1.33,0.05,-38568.0,3916.312,2675.322,7.6,---
312,2026-01,126904.0,28.303707,146169.80,---,90.90,5.25,---,2.38,0,-29240.0,---,---,---,---
313,2026-02,131630.0,28.303709,154370.40,---,90.75,5.25,---,2.86,0,37804.0,---,---,---,---
314,2026-03,115395.0,28.309308,147395.00,---,92.82,5.25,---,3.12,0,-125736.0,---,---,---,---

In [52]:
forecast_USDINR_df = pd.read_csv("/content/df_confidence_USDINR.csv")

In [53]:
forecast_USDINR_df

    Unnamed: 0  lower USDINR  upper USDINR
0   2024-04-01     81.382408     84.707330
1   2024-05-01     80.365178     85.729237
2   2024-06-01     79.612383     86.482471
3   2024-07-01     78.994971     87.099924
4   2024-08-01     78.459729     87.635171
5   2024-09-01     77.980700     88.114199
6   2024-10-01     77.543203     88.551697
7   2024-11-01     77.138007     88.956893
8   2024-12-01     76.758865     89.336035
9   2025-01-01     76.401317     89.693583
10  2025-02-01     76.062046     90.032854
11  2025-03-01     75.738506     90.356393
12  2025-04-01     75.428694     90.666206
13  2025-05-01     75.130997     90.963902
14  2025-06-01     74.844096     91.250803
15  2025-07-01     74.566896     91.528003
16  2025-08-01     74.298474     91.796425
17  2025-09-01     74.038046     92.056854
18  2025-10-01     73.784937     92.309963
19  2025-11-01     73.538563     92.556337
20  2025-12-01     73.298413     92.796486
21  2026-01-01     73.064039     93.030861
22  2026-02-01     72.835042     93.259858
23  2026-03-01     72.611068     93.483832
24  2026-04-01     72.391801     93.703098
25  2026-05-01     72.176956     93.917943
26  2026-06-01     71.966276     94.128624
27  2026-07-01     71.759527     94.335373
28  2026-08-01     71.556498     94.538402
29  2026-09-01     71.356993     94.737906
30  2026-10-01     71.160837     94.934062
31  2026-11-01     70.967866     95.127033
32  2026-12-01     70.777930     95.316970
33  2027-01-01     70.590889     95.504010
34  2027-02-01     70.406616     95.688284
35  2027-03-01     70.224990     95.869909
36  2027-04-01     70.045902     96.048998
37  2027-05-01     69.869247     96.225653
38  2027-06-01     69.694928     96.399971
39  2027-07-01     69.522857     96.572042
40  2027-08-01     69.352947     96.741952
41  2027-09-01     69.185120     96.909779
42  2027-10-01     69.019301     97.075599
43  2027-11-01     68.855419     97.239481
44  2027-12-01     68.693408     97.401492
45  2028-01-01     68.533205     97.561695
46  2028-02-01     68.374751     97.720149
47  2028-03-01     68.217990     97.876910

In [54]:
forecast_inflation_df = pd.read_csv("/content/forecast_df_Inflation.csv")

In [55]:
forecast_inflation_df

,Unnamed: 0,Date,Inflation_Predicted,Inflation_Lower_CI,Inflation_Upper_CI
0,0,2026-04-01,5.057206,3.347294,6.767119
1,1,2026-05-01,4.409001,1.760730,7.057271
2,2,2026-06-01,4.545830,1.213732,7.877927
3,3,2026-07-01,5.057355,1.159611,8.955099
4,4,2026-08-01,5.092870,0.701749,9.483991
5,5,2026-09-01,4.875139,0.040733,9.709545
6,6,2026-10-01,4.373693,-0.866634,9.614019
7,7,2026-11-01,3.927628,-1.689360,9.544616
8,8,2026-12-01,3.852456,-2.117476,9.822389
9,9,2027-01-01,4.259418,-2.043726,10.562562
10,10,2027-02-01,4.199211,-2.420393,10.818816
11,11,2027-03-01,3.571902,-3.349709,10.493514
12,12,2027-04-01,2.941943,-4.419274,10.303161
13,13,2027-05-01,2.478933,-5.325986,10.283852
14,14,2027-06-01,2.919276,-5.305442,11.143995
15,15,2027-07-01,4.907219,-3.716889,13.531327
16,16,2027-08-01,4.479746,-4.526056,13.485548
17,17,2027-09-01,3.119978,-6.251986,12.491942
18,18,2027-10-01,2.870603,-6.853745,12.594951
19,19,2027-11-01,3.232195,-6.832207,13.296597
20,20,2027-12-01,3.311353,-7.081983,13.704688
21,21,2028-01-01,3.003255,-7.708918,13.715428
22,22,2028-02-01,2.979059,-8.042733,14.000850
23,23,2028-03-01,2.629543,-8.693405,13.952490
24,24,2028-04-01,2.600031,-9.394494,14.594555
25,25,2028-05-01,2.004191,-10.706466,14.714848
26,26,2028-06-01,2.226842,-11.161697,15.615382
27,27,2028-07-01,3.155842,-10.877874,17.189558
28,28,2028-08-01,3.060441,-11.590066,17.710949
29,29,2028-09-01,2.519787,-12.722574,17.762147
30,30,2028-10-01,2.089616,-13.722460,17.901692
31,31,2028-11-01,1.871926,-14.490041,18.233892
32,32,2028-12-01,1.840392,-15.053575,18.734359
33,33,2029-01-01,2.045163,-15.364556,19.454882
34,34,2029-02-01,1.995138,-15.915487,19.905764
35,35,2029-03-01,1.446379,-16.951520,19.844278
36,36,2029-04-01,0.986203,-18.062965,20.035371
37,37,2029-05-01,0.485633,-19.227252,20.198519
38,38,2029-06-01,0.864422,-19.490551,21.219395
39,39,2029-07-01,2.552936,-18.424480,23.530353
40,40,2029-08-01,2.219360,-19.362555,23.801276
41,41,2029-09-01,1.091207,-21.078731,23.261144
42,42,2029-10-01,0.790709,-21.952053,23.533471
43,43,2029-11-01,0.988503,-22.313006,24.290011
44,44,2029-12-01,1.036361,-22.810806,24.883528
45,45,2030-01-01,0.873283,-23.507333,25.253899
46,46,2030-02-01,0.841783,-24.060857,25.744424
47,47,2030-03-01,0.435929,-24.978016,25.849873

In [56]:
forecast_FPI_df = pd.read_csv("/content/forecast_df_FPI.csv")

In [57]:
forecast_FPI_df

    Unnamed: 0        Date      Forecast      Lower_CI      Upper_CI
0            0  2026-04-01 -16163.444931 -99221.594437  43948.777052
1            1  2026-05-01  -7392.243283 -90099.792621  49842.665779
2            2  2026-06-01  -2489.564210 -84929.081907  53196.653923
3            3  2026-07-01    637.442061 -81339.915841  55534.593750
4            4  2026-08-01   2375.808833 -78850.201980  57166.359778
5            5  2026-09-01   3568.748853 -77125.136370  58307.002229
6            6  2026-10-01   4394.532631 -75932.048141  59105.942030
7            7  2026-11-01   4967.691242 -75109.157411  59667.075917
8            8  2026-12-01   5366.014521 -74543.930210  60062.680340
9            9  2027-01-01   5643.030491 -74158.064298  60343.050459
10          10  2027-02-01   5835.765550 -73897.064178  60543.192532
11          11  2027-03-01   5969.898483 -73722.996959  60687.474911
12          12  2027-04-01   6063.264318 -73609.455553  60792.862382
13          13  2027-05-01   6128.261209 -73538.055127  60871.166288
14          14  2027-06-01   6173.512651 -73495.995283  60930.610381
15          15  2027-07-01   6205.018872 -73474.363425  60976.920701
16          16  2027-08-01   6226.955848 -73466.953763  61014.084267
17          17  2027-09-01   6242.230405 -73469.445158  61044.877268
18          18  2027-10-01   6252.866161 -73478.828727  61071.232803
19          19  2027-11-01   6260.271988 -73493.009317  61094.496926
20          20  2027-12-01   6265.428816 -73510.528014  61115.606927
21          21  2028-01-01   6269.019641 -73530.368932  61135.215465
22          22  2028-02-01   6271.520031 -73551.824677  61153.777005
23          23  2028-03-01   6273.261126 -73574.402669  61171.608006
24          24  2028-04-01   6274.473505 -73597.759906  61188.928827
25          25  2028-05-01   6275.317722 -73621.657547  61205.892914
26          26  2028-06-01   6275.905579 -73645.929280  61222.607114
27          27  2028-07-01   6276.314922 -73670.459296  61239.145833
28          28  2028-08-01   6276.599962 -73695.166956  61255.560880
29          29  2028-09-01   6276.798445 -73719.996109  61271.888336
30          30  2028-10-01   6276.936655 -73744.907658  61288.153322
31          31  2028-11-01   6277.032896 -73769.874379  61304.373337
32          32  2028-12-01   6277.099911 -73794.877317  61320.560563
33          33  2029-01-01   6277.146576 -73819.903277  61336.723488
34          34  2029-02-01   6277.179071 -73844.943069  61352.868019
35          35  2029-03-01   6277.201698 -73869.990298  61368.998275
36          36  2029-04-01   6277.217454 -73895.040513  61385.117124
37          37  2029-05-01   6277.228425 -73920.090616  61401.226563
38          38  2029-06-01   6277.236065 -73945.138451  61417.327985
39          39  2029-07-01   6277.241385 -73970.182519  61433.422362
40          40  2029-08-01   6277.245089 -73995.221779  61449.510372
41          41  2029-09-01   6277.247669 -74020.255507  61465.592486
42          42  2029-10-01   6277.249465 -74045.283201  61481.669036
43          43  2029-11-01   6277.250716 -74070.304514  61497.740254
44          44  2029-12-01   6277.251587 -74095.319205  61513.806302
45          45  2030-01-01   6277.252193 -74120.327109  61529.867294
46          46  2030-02-01   6277.252616 -74145.328114  61545.923312
47          47  2030-03-01   6277.252910 -74170.322141  61561.974414

In [58]:
forecast_Repo_Rate_df = pd.read_csv("/content/confidence_df_RepoRate.csv")

In [59]:
forecast_Repo_Rate_df

    Unnamed: 0  Lower Repo Rate  Upper Repo Rate
0   2024-04-01         6.182519         6.817497
1   2024-05-01         6.168630         6.831377
2   2024-06-01         6.160165         6.839837
3   2024-07-01         6.154935         6.845065
4   2024-08-01         6.151678         6.848320
5   2024-09-01         6.149639         6.850357
6   2024-10-01         6.148361         6.851635
7   2024-11-01         6.147557         6.852439
8   2024-12-01         6.147051         6.852944
9   2025-01-01         6.146732         6.853263
10  2025-02-01         6.146531         6.853464
11  2025-03-01         6.146405         6.853590
12  2025-04-01         6.146325         6.853670
13  2025-05-01         6.146275         6.853720
14  2025-06-01         6.146243         6.853752
15  2025-07-01         6.146223         6.853772
16  2025-08-01         6.146211         6.853784
17  2025-09-01         6.146203         6.853792
18  2025-10-01         6.146198         6.853797
19  2025-11-01         6.146195         6.853800
20  2025-12-01         6.146193         6.853802
21  2026-01-01         6.146191         6.853803
22  2026-02-01         6.146191         6.853804
23  2026-03-01         6.146190         6.853805
24  2026-04-01         6.146190         6.853805
25  2026-05-01         6.146190         6.853805
26  2026-06-01         6.146189         6.853805
27  2026-07-01         6.146189         6.853805
28  2026-08-01         6.146189         6.853805
29  2026-09-01         6.146189         6.853806
30  2026-10-01         6.146189         6.853806
31  2026-11-01         6.146189         6.853806
32  2026-12-01         6.146189         6.853806
33  2027-01-01         6.146189         6.853806
34  2027-02-01         6.146189         6.853806
35  2027-03-01         6.146189         6.853806
36  2027-04-01         6.146189         6.853806
37  2027-05-01         6.146189         6.853806
38  2027-06-01         6.146189         6.853806
39  2027-07-01         6.146189         6.853806
40  2027-08-01         6.146189         6.853806
41  2027-09-01         6.146189         6.853806
42  2027-10-01         6.146189         6.853806
43  2027-11-01         6.146189         6.853806
44  2027-12-01         6.146189         6.853806
45  2028-01-01         6.146189         6.853806
46  2028-02-01         6.146189         6.853806
47  2028-03-01         6.146189         6.853806

In [60]:
forecast_GoldRes_df = pd.read_csv("/content/confidence_df_GoldReserves.csv")

In [61]:
forecast_GoldRes_df

    Unnamed: 0          Lower          Upper
0   2024-04-01   49922.503653   58837.942887
1   2024-05-01   51909.140414   60845.410303
2   2024-06-01   54719.103957   63676.156058
3   2024-07-01   56903.583659   65881.369864
4   2024-08-01   59202.384816   68200.857350
5   2024-09-01   61644.426122   70663.537539
6   2024-10-01   63955.725390   72995.428569
7   2024-11-01   66300.925123   75361.173263
8   2024-12-01   68669.725471   77750.472090
9   2025-01-01   71011.818948   80113.017878
10  2025-02-01   73362.828341   82484.433724
11  2025-03-01   75717.425529   84859.391815
12  2025-04-01   78066.701163   87228.983105
13  2025-05-01   80418.174111   89600.726762
14  2025-06-01   82770.129202   91972.907912
15  2025-07-01   85121.062139   94344.022552
16  2025-08-01   87472.523916   96715.621967
17  2025-09-01   89824.045292   99087.237203
18  2025-10-01   92175.389313  101458.631591
19  2025-11-01   94526.868819  103830.118251
20  2025-12-01   96878.365983  106201.579635
21  2026-01-01   99229.847568  108572.982780
22  2026-02-01  101581.375187  110944.389573
23  2026-03-01  103932.920780  113315.772224
24  2026-04-01  106284.480684  115687.127333
25  2026-05-01  108636.066663  118058.466931
26  2026-06-01  110987.672224  120429.784785
27  2026-07-01  113339.297183  122801.080970
28  2026-08-01  115690.943646  125172.357845
29  2026-09-01  118042.610081  127543.614134
30  2026-10-01  120394.296487  129914.850085
31  2026-11-01  122746.003146  132286.066229
32  2026-12-01  125097.729634  134657.262386
33  2027-01-01  127449.475883  137028.438730
34  2027-02-01  129801.241841  139399.595452
35  2027-03-01  132153.027328  141770.732608
36  2027-04-01  134504.832242  144141.850331
37  2027-05-01  136856.656477  146512.948749
38  2027-06-01  139208.499905  148884.027966
39  2027-07-01  141560.362416  151255.088099
40  2027-08-01  143912.243899  153626.129263
41  2027-09-01  146264.144239  155997.151568
42  2027-10-01  148616.063327  158368.155127
43  2027-11-01  150968.001052  160739.140048
44  2027-12-01  153319.957306  163110.106440
45  2028-01-01  155671.931980  165481.054412
46  2028-02-01  158023.924969  167851.984069
47  2028-03-01  160375.936166  170222.895518

In [62]:
forecast_GDP_df = pd.read_csv("/content/confidence_df_GDP.csv")

In [63]:
forecast_GDP_df

    Unnamed: 0    Lower GDP    Upper GDP
0   2024-01-01  3603.604276  3800.155569
1   2024-02-01  3562.897171  3840.862675
2   2024-03-01  3531.661510  3872.098335
3   2024-04-01  3505.328630  3898.431215
4   2024-05-01  3482.128897  3921.630949
5   2024-06-01  3461.154735  3942.605110
6   2024-07-01  3441.867003  3961.892843
7   2024-08-01  3423.914419  3979.845427
8   2024-09-01  3407.052984  3996.706862
9   2024-10-01  3391.105042  4012.654804
10  2024-11-01  3375.936478  4027.823368
11  2024-12-01  3361.443098  4042.316748
12  2025-01-01  3564.305072  4299.835205
13  2025-02-01  3538.871643  4325.268634
14  2025-03-01  3514.986251  4349.154026
15  2025-04-01  3492.396530  4371.743746
16  2025-05-01  3470.912038  4393.228239
17  2025-06-01  3450.384861  4413.755416
18  2025-07-01  3430.697404  4433.442873
19  2025-08-01  3411.754339  4452.385938
20  2025-09-01  3393.477116  4470.663161
21  2025-10-01  3375.800100  4488.340177
22  2025-11-01  3358.667777  4505.472500
23  2025-12-01  3342.032698  4522.107578
24  2026-01-01  3517.701327  4772.670982
25  2026-02-01  3482.366242  4808.006067
26  2026-03-01  3448.821836  4841.550473
27  2026-04-01  3416.820661  4873.551648
28  2026-05-01  3386.167499  4904.204811
29  2026-06-01  3356.705116  4933.667193
30  2026-07-01  3328.304660  4962.067649
31  2026-08-01  3300.858965  4989.513345
32  2026-09-01  3274.277760  5016.094549
33  2026-10-01  3248.484164  5041.888145
34  2026-11-01  3223.412057  5066.960252
35  2026-12-01  3199.004082  5091.368228
36  2027-01-01  3384.789461  5351.771436
37  2027-02-01  3348.845051  5387.715846
38  2027-03-01  3314.125557  5422.435340
39  2027-04-01  3280.513680  5456.047217
40  2027-05-01  3247.909729  5488.651168
41  2027-06-01  3216.228125  5520.332772
42  2027-07-01  3185.394755  5551.166142
43  2027-08-01  3155.344931  5581.215967
44  2027-09-01  3126.021789  5610.539108
45  2027-10-01  3097.375029  5639.185868
46  2027-11-01  3069.359900  5667.200997
47  2027-12-01  3041.936376  5694.624521

In [64]:
usdinr_ci = forecast_USDINR_df.rename(columns={
    "Unnamed: 0": "Date",
    "lower USDINR": "USDINR_Lower",
    "upper USDINR": "USDINR_Upper"
})[["Date","USDINR_Lower","USDINR_Upper"]]

In [65]:
repo_ci = forecast_Repo_Rate_df.rename(columns={
    "Unnamed: 0":"Date",
    "Lower Repo Rate":"Repo_Rate_Lower",
    "Upper Repo Rate":"Repo_Rate_Upper"
})[["Date","Repo_Rate_Lower","Repo_Rate_Upper"]]

In [66]:
gold_ci = forecast_GoldRes_df.rename(columns={
    "Unnamed: 0":"Date",
    "Lower":"GoldReserve_Lower",
    "Upper":"GoldReserve_Upper"
})[["Date","GoldReserve_Lower","GoldReserve_Upper"]]

In [67]:
gdp_ci = forecast_GDP_df.rename(columns={
    "Unnamed: 0":"Date",
    "Lower GDP":"GDP_Lower",
    "Upper GDP":"GDP_Upper"
})[["Date","GDP_Lower","GDP_Upper"]]

In [68]:
inflation_ci = forecast_inflation_df.rename(columns={
    "Inflation_Lower_CI":"Inflation_Lower",
    "Inflation_Upper_CI":"Inflation_Upper"
})[["Date","Inflation_Lower","Inflation_Upper"]]

In [69]:
fpi_ci = forecast_FPI_df.rename(columns={
    "Lower_CI":"FPI_Lower",
    "Upper_CI":"FPI_Upper"
})[["Date","FPI_Lower","FPI_Upper"]]

In [70]:
dfs = [usdinr_ci, repo_ci, gold_ci, gdp_ci, inflation_ci, fpi_ci]

for df in dfs:
    df["Date"] = pd.to_datetime(df["Date"])

In [71]:
end_date = pd.Timestamp("2027-12-01")

dfs = [
    df[df["Date"] <= end_date].copy()
    for df in dfs
]

In [72]:
ci_master = dfs[0]

for df in dfs[1:]:
    ci_master = ci_master.merge(
        df,
        on="Date",
        how="outer"
    )

ci_master = ci_master.sort_values("Date").reset_index(drop=True)

In [73]:
ci_master

,Date,USDINR_Lower,USDINR_Upper,Repo_Rate_Lower,Repo_Rate_Upper,GoldReserve_Lower,GoldReserve_Upper,GDP_Lower,GDP_Upper,Inflation_Lower,Inflation_Upper,FPI_Lower,FPI_Upper
0,2024-01-01,NaN,NaN,NaN,NaN,NaN,NaN,3603.604276,3800.155569,NaN,NaN,NaN,NaN
1,2024-02-01,NaN,NaN,NaN,NaN,NaN,NaN,3562.897171,3840.862675,NaN,NaN,NaN,NaN
2,2024-03-01,NaN,NaN,NaN,NaN,NaN,NaN,3531.661510,3872.098335,NaN,NaN,NaN,NaN
3,2024-04-01,81.382408,84.707330,6.182519,6.817497,49922.503653,58837.942887,3505.328630,3898.431215,NaN,NaN,NaN,NaN
4,2024-05-01,80.365178,85.729237,6.168630,6.831377,51909.140414,60845.410303,3482.128897,3921.630949,NaN,NaN,NaN,NaN
5,2024-06-01,79.612383,86.482471,6.160165,6.839837,54719.103957,63676.156058,3461.154735,3942.605110,NaN,NaN,NaN,NaN
6,2024-07-01,78.994971,87.099924,6.154935,6.845065,56903.583659,65881.369864,3441.867003,3961.892843,NaN,NaN,NaN,NaN
7,2024-08-01,78.459729,87.635171,6.151678,6.848320,59202.384816,68200.857350,3423.914419,3979.845427,NaN,NaN,NaN,NaN
8,2024-09-01,77.980700,88.114199,6.149639,6.850357,61644.426122,70663.537539,3407.052984,3996.706862,NaN,NaN,NaN,NaN
9,2024-10-01,77.543203,88.551697,6.148361,6.851635,63955.725390,72995.428569,3391.105042,4012.654804,NaN,NaN,NaN,NaN
10,2024-11-01,77.138007,88.956893,6.147557,6.852439,66300.925123,75361.173263,3375.936478,4027.823368,NaN,NaN,NaN,NaN
11,2024-12-01,76.758865,89.336035,6.147051,6.852944,68669.725471,77750.472090,3361.443098,4042.316748,NaN,NaN,NaN,NaN
12,2025-01-01,76.401317,89.693583,6.146732,6.853263,71011.818948,80113.017878,3564.305072,4299.835205,NaN,NaN,NaN,NaN
13,2025-02-01,76.062046,90.032854,6.146531,6.853464,73362.828341,82484.433724,3538.871643,4325.268634,NaN,NaN,NaN,NaN
14,2025-03-01,75.738506,90.356393,6.146405,6.853590,75717.425529,84859.391815,3514.986251,4349.154026,NaN,NaN,NaN,NaN
15,2025-04-01,75.428694,90.666206,6.146325,6.853670,78066.701163,87228.983105,3492.396530,4371.743746,NaN,NaN,NaN,NaN
16,2025-05-01,75.130997,90.963902,6.146275,6.853720,80418.174111,89600.726762,3470.912038,4393.228239,NaN,NaN,NaN,NaN
17,2025-06-01,74.844096,91.250803,6.146243,6.853752,82770.129202,91972.907912,3450.384861,4413.755416,NaN,NaN,NaN,NaN
18,2025-07-01,74.566896,91.528003,6.146223,6.853772,85121.062139,94344.022552,3430.697404,4433.442873,NaN,NaN,NaN,NaN
19,2025-08-01,74.298474,91.796425,6.146211,6.853784,87472.523916,96715.621967,3411.754339,4452.385938,NaN,NaN,NaN,NaN
20,2025-09-01,74.038046,92.056854,6.146203,6.853792,89824.045292,99087.237203,3393.477116,4470.663161,NaN,NaN,NaN,NaN
21,2025-10-01,73.784937,92.309963,6.146198,6.853797,92175.389313,101458.631591,3375.800100,4488.340177,NaN,NaN,NaN,NaN
22,2025-11-01,73.538563,92.556337,6.146195,6.853800,94526.868819,103830.118251,3358.667777,4505.472500,NaN,NaN,NaN,NaN
23,2025-12-01,73.298413,92.796486,6.146193,6.853802,96878.365983,106201.579635,3342.032698,4522.107578,NaN,NaN,NaN,NaN
24,2026-01-01,73.064039,93.030861,6.146191,6.853803,99229.847568,108572.982780,3517.701327,4772.670982,NaN,NaN,NaN,NaN
25,2026-02-01,72.835042,93.259858,6.146191,6.853804,101581.375187,110944.389573,3482.366242,4808.006067,NaN,NaN,NaN,NaN
26,2026-03-01,72.611068,93.483832,6.146190,6.853805,103932.920780,113315.772224,3448.821836,4841.550473,NaN,NaN,NaN,NaN
27,2026-04-01,72.391801,93.703098,6.146190,6.853805,106284.480684,115687.127333,3416.820661,4873.551648,3.347294,6.767119,-99221.594437,43948.777052
28,2026-05-01,72.176956,93.917943,6.146190,6.853805,108636.066663,118058.466931,3386.167499,4904.204811,1.760730,7.057271,-90099.792621,49842.665779
29,2026-06-01,71.966276,94.128624,6.146189,6.853805,110987.672224,120429.784785,3356.705116,4933.667193,1.213732,7.877927,-84929.081907,53196.653923
30,2026-07-01,71.759527,94.335373,6.146189,6.853805,113339.297183,122801.080970,3328.304660,4962.067649,1.159611,8.955099,-81339.915841,55534.593750
31,2026-08-01,71.556498,94.538402,6.146189,6.853805,115690.943646,125172.357845,3300.858965,4989.513345,0.701749,9.483991,-78850.201980,57166.359778
32,2026-09-01,71.356993,94.737906,6.146189,6.853806,118042.610081,127543.614134,3274.277760,5016.094549,0.040733,9.709545,-77125.136370,58307.002229
33,2026-10-01,71.160837,94.934062,6.146189,6.853806,120394.296487,129914.850085,3248.484164,5041.888145,-0.866634,9.614019,-75932.048141,59105.942030
34,2026-11-01,70.967866,95.127033,6.146189,6.853806,122746.003146,132286.066229,3223.412057,5066.960252,-1.689360,9.544616,-75109.157411,59667.075917
35,2026-12-01,70.777930,95.316970,6.146189,6.853806,125097.729634,134657.262386,3199.004082,5091.368228,-2.117476,9.822389,-74543.930210,60062.680340
36,2027-01-01,70.590889,95.504010,6.146189,6.853806,127449.475883,137028.438730,3384.789461,5351.771436,-2.043726,10.562562,-74158.064298,60343.050459
37,2027-02-01,70.406616,95.688284,6.146189,6.853806,129801.241841,139399.595452,3348.845051,5387.715846,-2.420393,10.818816,-73897.064178,60543.192532
38,2027-03-01,70.224990,95.869909,6.146189,6.853806,132153.027328,141770.732608,3314.125557,5422.435340,-3.349709,10.493514,-73722.996959,60687.474911
39,2027-04-01,70.045902,96.048998,6.146189,6.853806,134504.832242,144141.850331,3280.513680,5456.047217,-4.419274,10.303161,-73609.455553,60792.862382
40,2027-05-01,69.869247,96.225653,6.146189,6.853806,136856.656477,146512.948749,3247.909729,5488.651168,-5.325986,10.283852,-73538.055127,60871.166288
41,2027-06-01,69.694928,96.399971,6.146189,6.853806,139208.499905,148884.027966,3216.228125,5520.332772,-5.305442,11.143995,-73495.995283,60930.610381
42,2027-07-01,69.522857,96.572042,6.146189,6.853806,141560.362416,151255.088099,3185.394755,5551.166142,-3.716889,13.531327,-73474.363425,60976.920701
43,2027-08-01,69.352947,96.741952,6.146189,6.853806,143912.243899,153626.129263,3155.344931,5581.215967,-4.526056,13.485548,-73466.953763,61014.084267
44,2027-09-01,69.185120,96.909779,6.146189,6.853806,146264.144239,155997.151568,3126.021789,5610.539108,-6.251986,12.491942,-73469.445158,61044.877268
45,2027-10-01,69.019301,97.075599,6.146189,6.853806,148616.063327,158368.155127,3097.375029,5639.185868,-6.853745,12.594951,-73478.828727,61071.232803
46,2027-11-01,68.855419,97.239481,6.146189,6.853806,150968.001052,160739.140048,3069.359900,5667.200997,-6.832207,13.296597,-73493.009317,61094.496926
47,2027-12-01,68.693408,97.401492,6.146189,6.853806,153319.957306,163110.106440,3041.936376,5694.624521,-7.081983,13.704688,-73510.528014,61115.606927

In [86]:
main_df[(main_df['Date'] >= "2024-01") & (main_df['Date'] <= "2024-03")]

,Date,Gold_Reservs_USD_mn,Gold_Volume_mn_troy_oz,Gold_Price[/10gm],Gold_CPI,USDINR,Repo_Rate,Overall_CPI,Inflation_YoY,Inflation_MoM,FPI_Net_INR_Crore,"GDP, current prices (Billions of U.S. dollars)","GDP per capita, current prices\n (U.S. dollars per capita)",Real GDP growth (Annual percent change),Remittances received (Personal remittances received current U.S. $)
288,2024-01,47967.45,26.087061,62313.32,208.6,83.11,6.5,185.5,5.1,-0.11,-6593.0,3760.814,2591.992,7.1,137674533895.686005
289,2024-02,48047.84,26.267061,62057.24,208.4,82.95,6.5,185.8,5.09,0.16,31817.0,3760.814,2591.992,7.1,137674533895.686005
290,2024-03,52674.83,26.431049,65176.21,216.5,83.02,6.5,185.8,4.85,0,51996.0,3760.814,2591.992,7.1,137674533895.686005

In [83]:
main_df[(main_df['Date'] >= "2024-01") & (main_df['Date'] <= "2026-03")][["Date","Inflation_YoY","FPI_Net_INR_Crore"]]

        Date Inflation_YoY  FPI_Net_INR_Crore
288  2024-01           5.1            -6593.0
289  2024-02          5.09            31817.0
290  2024-03          4.85            51996.0
291  2024-04          4.83           -16260.0
292  2024-05           4.8           -12911.0
293  2024-06          5.08            41757.0
294  2024-07           3.6            48796.0
295  2024-08          3.65            25493.0
296  2024-09          5.49            93538.0
297  2024-10          6.21           -96358.0
298  2024-11          5.48           -21444.0
299  2024-12          5.22            25938.0
300  2025-01          4.26           -77211.0
301  2025-02          3.61           -24301.0
302  2025-03          3.34            32981.0
303  2025-04          3.16           -20190.0
304  2025-05          2.82            30950.0
305  2025-06           2.1            -7563.0
306  2025-07          1.61            -5538.0
307  2025-08          2.07           -20505.0
308  2025-09          1.44           -12539.0
309  2025-10          0.25            35598.0
310  2025-11          0.71             2836.0
311  2025-12          1.33           -38568.0
312  2026-01          2.38           -29240.0
313  2026-02          2.86            37804.0
314  2026-03          3.12          -125736.0

In [85]:
ci_master.to_excel("ci_master.xlsx")