<a href="https://colab.research.google.com/github/UKD1211/Macroeconomic_impact_of_gold-_Econ_growth/blob/main/Research_proj_TSA_data.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [78]:
import pandas as pd
import numpy as np

In [79]:
df_gold_reservs = pd.read_excel("/content/Gold Reserves USD mn Monthly India.xlsx")

In [80]:
df_gold_reservs

              Unnamed: 0 Gold Reserves: USD mn: Monthly: India
0                 Region                                 India
1            Subnational                                   NaN
2              Frequency                               Monthly
3                   Unit                                USD mn
4                 Source                             CEIC Data
..                   ...                                   ...
855  2025-11-01 00:00:00                                106740
856  2025-12-01 00:00:00                                111262
857  2026-01-01 00:00:00                                126904
858  2026-02-01 00:00:00                                131630
859  2026-03-01 00:00:00                                115395

[860 rows x 2 columns]

In [81]:
df_gold_reservs.columns = ["Date", "Gold_Reservs_USD_mn"]

In [82]:
df_gold_reservs

                    Date Gold_Reservs_USD_mn
0                 Region               India
1            Subnational                 NaN
2              Frequency             Monthly
3                   Unit              USD mn
4                 Source           CEIC Data
..                   ...                 ...
855  2025-11-01 00:00:00              106740
856  2025-12-01 00:00:00              111262
857  2026-01-01 00:00:00              126904
858  2026-02-01 00:00:00              131630
859  2026-03-01 00:00:00              115395

[860 rows x 2 columns]

In [83]:
df_gold_reservs = df_gold_reservs.copy()

df_gold_reservs['Date'] = pd.to_datetime(
    df_gold_reservs['Date'],
    errors='coerce'
)

df_gold_reservs = df_gold_reservs[
    df_gold_reservs['Date'].notna()
]

df_gold_reservs['Gold_Reservs_USD_mn'] = pd.to_numeric(
    df_gold_reservs['Gold_Reservs_USD_mn'],
    errors='coerce'
)

df_gold_reservs = df_gold_reservs[
    df_gold_reservs['Date'] >= '2000-01-01'
]

df_gold_reservs.reset_index(drop=True, inplace=True)

/tmp/ipykernel_14993/3182504132.py:3: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  df_gold_reservs['Date'] = pd.to_datetime(

In [84]:
df_gold_reservs['Date'] = df_gold_reservs['Date'].dt.strftime('%Y-%m')

In [85]:
df_gold_reservs

        Date  Gold_Reservs_USD_mn
0    2000-01               2945.0
1    2000-02               3104.0
2    2000-03               2974.0
3    2000-04               2895.0
4    2000-05               2851.0
..       ...                  ...
310  2025-11             106740.0
311  2025-12             111262.0
312  2026-01             126904.0
313  2026-02             131630.0
314  2026-03             115395.0

[315 rows x 2 columns]

In [86]:
df_gold_reservs.describe()

       Gold_Reservs_USD_mn
count           315.000000
mean          23261.104943
std           22057.399171
min            2695.000000
25%            6397.500000
50%           20183.200000
75%           28130.500000
max          131630.000000

In [87]:
!pip install openpyxl
df_gold_reservs.to_excel(
    'clean_gold_reserves.xlsx',
    index=False
)

Requirement already satisfied: openpyxl in /usr/local/lib/python3.12/dist-packages (3.1.5)
Requirement already satisfied: et-xmlfile in /usr/local/lib/python3.12/dist-packages (from openpyxl) (2.0.0)

In [88]:
df_gold_volume = pd.read_excel("/content/International Liquidity Gold Volume.xlsx")

In [89]:
df_gold_volume

              Unnamed: 0 International Liquidity: Gold: Volume
0                 Region                                 India
1            Subnational                                   NaN
2              Frequency                               Monthly
3                   Unit                       Fine Troy oz mn
4                 Source           International Monetary Fund
..                   ...                                   ...
861  2025-11-01 00:00:00                             28.298487
862  2025-12-01 00:00:00                             28.303688
863  2026-01-01 00:00:00                             28.303707
864  2026-02-01 00:00:00                             28.303709
865  2026-03-01 00:00:00                             28.309308

[866 rows x 2 columns]

In [90]:
# Rename columns
df_gold_volume.columns = ['Date', 'Gold_Volume_mn_troy_oz']

# Convert Date column
df_gold_volume['Date'] = pd.to_datetime(
    df_gold_volume['Date'],
    errors='coerce'
)

# Keep only valid date rows
df_gold_volume = df_gold_volume[
    df_gold_volume['Date'].notna()
]

# Convert gold volume column to numeric
df_gold_volume['Gold_Volume_mn_troy_oz'] = pd.to_numeric(
    df_gold_volume['Gold_Volume_mn_troy_oz'],
    errors='coerce'
)

# Keep only data from 2000 onwards
df_gold_volume = df_gold_volume[
    df_gold_volume['Date'] >= '2000-01-01'
]

# Reset index
df_gold_volume.reset_index(drop=True, inplace=True)

# Preview cleaned dataframe
df_gold_volume.head()

/tmp/ipykernel_14993/2340691387.py:5: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  df_gold_volume['Date'] = pd.to_datetime(
/tmp/ipykernel_14993/2340691387.py:16: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_gold_volume['Gold_Volume_mn_troy_oz'] = pd.to_numeric(

        Date  Gold_Volume_mn_troy_oz
0 2000-01-01               11.502339
1 2000-02-01               11.502339
2 2000-03-01               11.502339
3 2000-04-01               11.502339
4 2000-05-01               11.502339

In [91]:
df_gold_volume['Date'] = df_gold_volume['Date'].dt.strftime('%Y-%m')

In [92]:
df_gold_volume

        Date  Gold_Volume_mn_troy_oz
0    2000-01               11.502339
1    2000-02               11.502339
2    2000-03               11.502339
3    2000-04               11.502339
4    2000-05               11.502339
..       ...                     ...
310  2025-11               28.298487
311  2025-12               28.303688
312  2026-01               28.303707
313  2026-02               28.303709
314  2026-03               28.309308

[315 rows x 2 columns]

In [93]:
df_gold_volume.to_excel(
    'clean_gold_volume.xlsx',
    index=False
)

In [94]:
df_gp_2020 = pd.read_csv("/content/Historical-Spot-Price-GOLD-01-01-2020-to-31-12-2020.csv")

In [95]:
df_gp_2020

,SYMBOL \n,QUOTATION VALUE \n,UPDATED DATE \n,SESSION 1 * SPOT PRICE (IN RS.) \n,SESSION 2 * SPOT PRICE (IN RS.) \n,POLLED INFORMATION \n
0,GOLD,10 Grams,31-DEC-2020,"49,913.00","49,996.00",https://nsearchives.nseindia.com/archives/com/...
1,GOLD,10 Grams,30-DEC-2020,"49,821.00","49,772.00",https://nsearchives.nseindia.com/archives/com/...
2,GOLD,10 Grams,29-DEC-2020,"49,821.00","49,898.00",https://nsearchives.nseindia.com/archives/com/...
3,GOLD,10 Grams,28-DEC-2020,"50,175.00","50,003.00",https://nsearchives.nseindia.com/archives/com/...
4,GOLD,10 Grams,24-DEC-2020,"49,893.00","49,879.00",https://nsearchives.nseindia.com/archives/com/...
...,...,...,...,...,...,...
201,GOLD,10 Grams,07-JAN-2020,"40,317.00","40,393.00",https://nsearchives.nseindia.com/archives/com/...
202,GOLD,10 Grams,06-JAN-2020,"40,782.00","40,696.00",https://nsearchives.nseindia.com/archives/com/...
203,GOLD,10 Grams,03-JAN-2020,"39,763.00","39,927.00",https://nsearchives.nseindia.com/archives/com/...
204,GOLD,10 Grams,02-JAN-2020,"39,064.00","39,030.00",https://nsearchives.nseindia.com/archives/com/...
205,GOLD,10 Grams,01-JAN-2020,"38,977.00","38,931.00",https://nsearchives.nseindia.com/archives/com/...

In [96]:
# Keep only required columns
# Clean column names first to remove any leading/trailing whitespace or newline characters
df_gp_2020.columns = df_gp_2020.columns.str.strip()
df_gp_2020.columns = df_gp_2020.columns.str.replace('\n', '')

df_gp_2020 = df_gp_2020[
    ['UPDATED DATE', 'SESSION 1 * SPOT PRICE (IN RS.)']
]

# Rename columns
df_gp_2020.columns = ['Date', 'Gold_Price']

# Remove commas from prices
df_gp_2020['Gold_Price'] = (
    df_gp_2020['Gold_Price']
    .astype(str)
    .str.replace(',', '')
)

# Convert Gold Price to numeric
df_gp_2020['Gold_Price'] = pd.to_numeric(
    df_gp_2020['Gold_Price'],
    errors='coerce'
)

# Convert Date column
df_gp_2020['Date'] = pd.to_datetime(
    df_gp_2020['Date'],
    format='%d-%b-%Y',
    errors='coerce'
)

# Remove invalid rows
df_gp_2020 = df_gp_2020[
    df_gp_2020['Date'].notna()
]

# Create Year-Month column
df_gp_2020['Date'] = df_gp_2020['Date'].dt.strftime('%Y-%m')

# Group by month and take average
df_gp_2020 = (
    df_gp_2020
    .groupby('Date', as_index=False)
    ['Gold_Price']
    .mean()
)

# Round values
df_gp_2020['Gold_Price'] = (
    df_gp_2020['Gold_Price']
    .round(2)
)

# Preview
df_gp_2020.head()

/tmp/ipykernel_14993/95477698.py:14: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_gp_2020['Gold_Price'] = (
/tmp/ipykernel_14993/95477698.py:21: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_gp_2020['Gold_Price'] = pd.to_numeric(
/tmp/ipykernel_14993/95477698.py:27: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_gp_2020['Date'] = pd.to_datetime(

      Date  Gold_Price
0  2020-01    39987.74
1  2020-02    41174.35
2  2020-03    42179.57
3  2020-06    47300.19
4  2020-07    49937.35

In [97]:
df_gp_2020

      Date  Gold_Price
0  2020-01    39987.74
1  2020-02    41174.35
2  2020-03    42179.57
3  2020-06    47300.19
4  2020-07    49937.35
5  2020-08    53144.75
6  2020-09    50904.50
7  2020-10    50659.43
8  2020-11    50453.32
9  2020-12    49479.14

In [98]:
df_gp_2021 = pd.read_csv("/content/Historical-Spot-Price-GOLD-01-01-2021-to-31-12-2021.csv")

In [99]:
# Clean column names
df_gp_2021.columns = df_gp_2021.columns.str.strip()
df_gp_2021.columns = df_gp_2021.columns.str.replace('\n', '')

# Keep only required columns
df_gp_2021 = df_gp_2021[
    ['UPDATED DATE', 'SESSION 1 * SPOT PRICE (IN RS.)']
]

# Rename columns
df_gp_2021.columns = ['Date', 'Gold_Price']

# Remove commas from prices
df_gp_2021['Gold_Price'] = (
    df_gp_2021['Gold_Price']
    .astype(str)
    .str.replace(',', '')
)

# Convert Gold Price to numeric
df_gp_2021['Gold_Price'] = pd.to_numeric(
    df_gp_2021['Gold_Price'],
    errors='coerce'
)

# Convert Date column
df_gp_2021['Date'] = pd.to_datetime(
    df_gp_2021['Date'],
    format='%d-%b-%Y',
    errors='coerce'
)

# Remove invalid rows
df_gp_2021 = df_gp_2021[
    df_gp_2021['Date'].notna()
]

# Convert to YYYY-MM
df_gp_2021['Date'] = (
    df_gp_2021['Date']
    .dt.strftime('%Y-%m')
)

# Monthly average gold price
df_gp_2021 = (
    df_gp_2021
    .groupby('Date', as_index=False)
    ['Gold_Price']
    .mean()
)

# Round values
df_gp_2021['Gold_Price'] = (
    df_gp_2021['Gold_Price']
    .round(2)
)

# Sort chronologically
df_gp_2021 = df_gp_2021.sort_values('Date')

# Reset index
df_gp_2021.reset_index(drop=True, inplace=True)

# Preview
df_gp_2021.head()

      Date  Gold_Price
0  2021-01    49620.90
1  2021-02    47166.85
2  2021-03    44741.33
3  2021-04    46486.16
4  2021-05    47931.95

In [100]:
df_gp_2021

       Date  Gold_Price
0   2021-01    49620.90
1   2021-02    47166.85
2   2021-03    44741.33
3   2021-04    46486.16
4   2021-05    47931.95
5   2021-06    47937.64
6   2021-07    47739.95
7   2021-08    47165.70
8   2021-09    46594.95
9   2021-10    47206.90
10  2021-11    48177.45
11  2021-12    47945.91

In [101]:
df_gp_2022 = pd.read_csv("/content/Historical-Spot-Price-GOLD-01-01-2022-to-31-12-2022(2).csv")

In [102]:
# Clean column names
df_gp_2022.columns = df_gp_2022.columns.str.strip()
df_gp_2022.columns = df_gp_2022.columns.str.replace('\n', '')

# Keep only required columns
df_gp_2022 = df_gp_2022[
    ['UPDATED DATE', 'SESSION 1 * SPOT PRICE (IN RS.)']
]

# Rename columns
df_gp_2022.columns = ['Date', 'Gold_Price']

# Remove commas from prices
df_gp_2022['Gold_Price'] = (
    df_gp_2022['Gold_Price']
    .astype(str)
    .str.replace(',', '')
)

# Convert Gold Price to numeric
df_gp_2022['Gold_Price'] = pd.to_numeric(
    df_gp_2022['Gold_Price'],
    errors='coerce'
)

# Convert Date column
df_gp_2022['Date'] = pd.to_datetime(
    df_gp_2022['Date'],
    format='%d-%b-%Y',
    errors='coerce'
)

# Remove invalid rows
df_gp_2022 = df_gp_2022[
    df_gp_2022['Date'].notna()
]

# Convert to YYYY-MM
df_gp_2022['Date'] = (
    df_gp_2022['Date']
    .dt.strftime('%Y-%m')
)

# Monthly average gold price
df_gp_2022 = (
    df_gp_2022
    .groupby('Date', as_index=False)
    ['Gold_Price']
    .mean()
)

# Round values
df_gp_2022['Gold_Price'] = (
    df_gp_2022['Gold_Price']
    .round(2)
)

# Sort chronologically
df_gp_2022 = df_gp_2022.sort_values('Date')

# Reset index
df_gp_2022.reset_index(drop=True, inplace=True)

# Preview
df_gp_2022.head()

      Date  Gold_Price
0  2022-01    48015.84
1  2022-02    49308.70
2  2022-03    51782.33
3  2022-04    51991.63
4  2022-05    50888.24

In [103]:
df_gp_2022

       Date  Gold_Price
0   2022-01    48015.84
1   2022-02    49308.70
2   2022-03    51782.33
3   2022-04    51991.63
4   2022-05    50888.24
5   2022-06    46519.23
6   2022-07    44034.38
7   2022-08    44731.50
8   2022-09    43279.91
9   2022-10    43923.19
10  2022-11    44967.33
11  2022-12    46776.67

In [104]:
df_gp_2023 = pd.read_csv("/content/Historical-Spot-Price-GOLD-01-01-2023-to-31-12-2023.csv")

In [105]:
# Clean column names
df_gp_2023.columns = df_gp_2023.columns.str.strip()
df_gp_2023.columns = df_gp_2023.columns.str.replace('\n', '')

# Keep only required columns
df_gp_2023 = df_gp_2023[
    ['UPDATED DATE', 'SESSION 1 * SPOT PRICE (IN RS.)']
]

# Rename columns
df_gp_2023.columns = ['Date', 'Gold_Price']

# Remove commas from prices
df_gp_2023['Gold_Price'] = (
    df_gp_2023['Gold_Price']
    .astype(str)
    .str.replace(',', '')
)

# Convert Gold Price to numeric
df_gp_2023['Gold_Price'] = pd.to_numeric(
    df_gp_2023['Gold_Price'],
    errors='coerce'
)

# Convert Date column
df_gp_2023['Date'] = pd.to_datetime(
    df_gp_2023['Date'],
    format='%d-%b-%Y',
    errors='coerce'
)

# Remove invalid rows
df_gp_2023 = df_gp_2023[
    df_gp_2023['Date'].notna()
]

# Convert to YYYY-MM
df_gp_2023['Date'] = (
    df_gp_2023['Date']
    .dt.strftime('%Y-%m')
)

# Monthly average gold price
df_gp_2023 = (
    df_gp_2023
    .groupby('Date', as_index=False)
    ['Gold_Price']
    .mean()
)

# Round values
df_gp_2023['Gold_Price'] = (
    df_gp_2023['Gold_Price']
    .round(2)
)

# Sort chronologically
df_gp_2023 = df_gp_2023.sort_values('Date')

# Reset index
df_gp_2023.reset_index(drop=True, inplace=True)

# Preview
df_gp_2023.head()

      Date  Gold_Price
0  2023-01    48803.24
1  2023-02    49056.35
2  2023-03    50009.57
3  2023-04    52160.59
4  2023-05    52532.91

In [106]:
df_gp_2023

       Date  Gold_Price
0   2023-01    48803.24
1   2023-02    49056.35
2   2023-03    50009.57
3   2023-04    52160.59
4   2023-05    52532.91
5   2023-06    51216.95
6   2023-07    51180.33
7   2023-08    50917.05
8   2023-09    50965.75
9   2023-10    55317.10
10  2023-11    60827.55
11  2023-12    62277.10

In [107]:
df_gp_2024 = pd.read_csv("/content/Historical-Spot-Price-GOLD-01-01-2024-to-31-12-2024.csv")

In [108]:
# Clean column names
df_gp_2024.columns = df_gp_2024.columns.str.strip()
df_gp_2024.columns = df_gp_2024.columns.str.replace('\n', '')

# Keep only required columns
df_gp_2024 = df_gp_2024[
    ['UPDATED DATE', 'SESSION 1 * SPOT PRICE (IN RS.)']
]

# Rename columns
df_gp_2024.columns = ['Date', 'Gold_Price']

# Remove commas from prices
df_gp_2024['Gold_Price'] = (
    df_gp_2024['Gold_Price']
    .astype(str)
    .str.replace(',', '')
)

# Convert Gold Price to numeric
df_gp_2024['Gold_Price'] = pd.to_numeric(
    df_gp_2024['Gold_Price'],
    errors='coerce'
)

# Convert Date column
df_gp_2024['Date'] = pd.to_datetime(
    df_gp_2024['Date'],
    format='%d-%b-%Y',
    errors='coerce'
)

# Remove invalid rows
df_gp_2024 = df_gp_2024[
    df_gp_2024['Date'].notna()
]

# Convert to YYYY-MM
df_gp_2024['Date'] = (
    df_gp_2024['Date']
    .dt.strftime('%Y-%m')
)

# Monthly average gold price
df_gp_2024 = (
    df_gp_2024
    .groupby('Date', as_index=False)
    ['Gold_Price']
    .mean()
)

# Round values
df_gp_2024['Gold_Price'] = (
    df_gp_2024['Gold_Price']
    .round(2)
)

# Sort chronologically
df_gp_2024 = df_gp_2024.sort_values('Date')

# Reset index
df_gp_2024.reset_index(drop=True, inplace=True)

# Preview
df_gp_2024.head()

      Date  Gold_Price
0  2024-01    62313.32
1  2024-02    62057.24
2  2024-03    65176.21
3  2024-04    71492.50
4  2024-05    72188.38

In [109]:
df_gp_2024

       Date  Gold_Price
0   2024-01    62313.32
1   2024-02    62057.24
2   2024-03    65176.21
3   2024-04    71492.50
4   2024-05    72188.38
5   2024-06    71595.16
6   2024-07    71556.70
7   2024-08    70400.43
8   2024-09    72851.52
9   2024-10    76680.68
10  2024-11    76263.11
11  2024-12    76263.81

In [110]:
df_gp_2025 = pd.read_csv("/content/Historical-Spot-Price-GOLD-01-01-2025-to-31-12-2025.csv")

In [111]:
# Clean column names
df_gp_2025.columns = df_gp_2025.columns.str.strip()
df_gp_2025.columns = df_gp_2025.columns.str.replace('\n', '')

# Keep only required columns
df_gp_2025 = df_gp_2025[
    ['UPDATED DATE', 'SESSION 1 * SPOT PRICE (IN RS.)']
]

# Rename columns
df_gp_2025.columns = ['Date', 'Gold_Price']

# Remove commas from prices
df_gp_2025['Gold_Price'] = (
    df_gp_2025['Gold_Price']
    .astype(str)
    .str.replace(',', '')
)

# Convert Gold Price to numeric
df_gp_2025['Gold_Price'] = pd.to_numeric(
    df_gp_2025['Gold_Price'],
    errors='coerce'
)

# Convert Date column
df_gp_2025['Date'] = pd.to_datetime(
    df_gp_2025['Date'],
    format='%d-%b-%Y',
    errors='coerce'
)

# Remove invalid rows
df_gp_2025 = df_gp_2025[
    df_gp_2025['Date'].notna()
]

# Convert to YYYY-MM
df_gp_2025['Date'] = (
    df_gp_2025['Date']
    .dt.strftime('%Y-%m')
)

# Monthly average gold price
df_gp_2025 = (
    df_gp_2025
    .groupby('Date', as_index=False)
    ['Gold_Price']
    .mean()
)

# Round values
df_gp_2025['Gold_Price'] = (
    df_gp_2025['Gold_Price']
    .round(2)
)

# Sort chronologically
df_gp_2025 = df_gp_2025.sort_values('Date')

# Reset index
df_gp_2025.reset_index(drop=True, inplace=True)

# Preview
df_gp_2025.head()

      Date  Gold_Price
0  2025-01    78642.13
1  2025-02    84888.40
2  2025-03    86902.26
3  2025-04    93147.63
4  2025-05    94673.95

In [112]:
df_gp_2025

       Date  Gold_Price
0   2025-01    78642.13
1   2025-02    84888.40
2   2025-03    86902.26
3   2025-04    93147.63
4   2025-05    94673.95
5   2025-06    97091.43
6   2025-07    97587.43
7   2025-08    99683.47
8   2025-09   109531.32
9   2025-10   122294.30
10  2025-11   122834.00
11  2025-12   131322.55

In [113]:
df_gp_2026 = pd.read_csv("/content/Historical-Spot-Price-GOLD-01-01-2026-to-28-02-2026.csv")

In [114]:
# Clean column names
df_gp_2026.columns = df_gp_2026.columns.str.strip()
df_gp_2026.columns = df_gp_2026.columns.str.replace('\n', '')

# Keep only required columns
df_gp_2026 = df_gp_2026[
    ['UPDATED DATE', 'SESSION 1 * SPOT PRICE (IN RS.)']
]

# Rename columns
df_gp_2026.columns = ['Date', 'Gold_Price']

# Remove commas from prices
df_gp_2026['Gold_Price'] = (
    df_gp_2026['Gold_Price']
    .astype(str)
    .str.replace(',', '')
)

# Convert Gold Price to numeric
df_gp_2026['Gold_Price'] = pd.to_numeric(
    df_gp_2026['Gold_Price'],
    errors='coerce'
)

# Convert Date column
df_gp_2026['Date'] = pd.to_datetime(
    df_gp_2026['Date'],
    format='%d-%b-%Y',
    errors='coerce'
)

# Remove invalid rows
df_gp_2026 = df_gp_2026[
    df_gp_2026['Date'].notna()
]

# Convert to YYYY-MM
df_gp_2026['Date'] = (
    df_gp_2026['Date']
    .dt.strftime('%Y-%m')
)

# Monthly average gold price
df_gp_2026 = (
    df_gp_2026
    .groupby('Date', as_index=False)
    ['Gold_Price']
    .mean()
)

# Round values
df_gp_2026['Gold_Price'] = (
    df_gp_2026['Gold_Price']
    .round(2)
)

# Sort chronologically
df_gp_2026 = df_gp_2026.sort_values('Date')

# Reset index
df_gp_2026.reset_index(drop=True, inplace=True)

# Preview
df_gp_2026.head()

      Date  Gold_Price
0  2026-01    146169.8
1  2026-02    154370.4

In [115]:
df_bombay_gp_2000_2019 = pd.read_csv(
    "/content/Gold India Bombay Market Standard.csv",
    header=3 # Assuming the actual header is on the 4th line (index 3)
)

In [116]:
df_bombay_gp_2000_2019

                Frequency\t"Daily   ""5 observation"""
0                  Unit\tINR/10 g                  NaN
1      Source\tThe Economic Times                  NaN
2                  Status\tActive                  NaN
3     Series ID\t19318401 (IDPBA)                  NaN
4              SR Code\tSR4729484                  NaN
...                           ...                  ...
5411              02-10-20\t40850                  NaN
5412              02-11-20\t40700                  NaN
5413              02-12-20\t40500                  NaN
5414            02/13/2020\t40850                  NaN
5415            02/14/2020\t40850                  NaN

[5416 rows x 2 columns]

In [117]:
# Rename first column
df_bombay_gp_2000_2019.columns = ['Raw_Data', 'Unused']

# Keep only first column
df_bombay_gp_2000_2019 = df_bombay_gp_2000_2019[['Raw_Data']]

# Remove rows with NaN
df_bombay_gp_2000_2019 = df_bombay_gp_2000_2019.dropna()

# Keep only rows containing dates
df_bombay_gp_2000_2019 = df_bombay_gp_2000_2019[
    df_bombay_gp_2000_2019['Raw_Data']
    .astype(str)
    .str.contains(r'\d{2}[-/]\d{2}[-/]\d{2,4}')
]

# Split date and price using tab separator
df_bombay_gp_2000_2019[
    ['Date', 'Gold_Price']
] = df_bombay_gp_2000_2019['Raw_Data'].str.split(
    '\t',
    expand=True
)

# Remove commas from price
df_bombay_gp_2000_2019['Gold_Price'] = (
    df_bombay_gp_2000_2019['Gold_Price']
    .astype(str)
    .str.replace(',', '')
)

# Convert Gold Price to numeric
df_bombay_gp_2000_2019['Gold_Price'] = pd.to_numeric(
    df_bombay_gp_2000_2019['Gold_Price'],
    errors='coerce'
)

# Convert Date column
df_bombay_gp_2000_2019['Date'] = pd.to_datetime(
    df_bombay_gp_2000_2019['Date'],
    errors='coerce'
)

# Remove invalid dates
df_bombay_gp_2000_2019 = df_bombay_gp_2000_2019[
    df_bombay_gp_2000_2019['Date'].notna()
]

# Keep only years 2000-2019
df_bombay_gp_2000_2019 = df_bombay_gp_2000_2019[
    (df_bombay_gp_2000_2019['Date'] >= '2000-01-01') &
    (df_bombay_gp_2000_2019['Date'] <= '2019-12-31')
]

# Convert to Year-Month
df_bombay_gp_2000_2019['Date'] = (
    df_bombay_gp_2000_2019['Date']
    .dt.strftime('%Y-%m')
)

# Monthly average gold price
df_bombay_gp_2000_2019 = (
    df_bombay_gp_2000_2019
    .groupby('Date', as_index=False)
    ['Gold_Price']
    .mean()
)

# Round values
df_bombay_gp_2000_2019['Gold_Price'] = (
    df_bombay_gp_2000_2019['Gold_Price']
    .round(2)
)

# Sort chronologically
df_bombay_gp_2000_2019 = (
    df_bombay_gp_2000_2019
    .sort_values('Date')
)

# Reset index
df_bombay_gp_2000_2019.reset_index(
    drop=True,
    inplace=True
)

# Preview
df_bombay_gp_2000_2019.head()

/tmp/ipykernel_14993/3800559204.py:39: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  df_bombay_gp_2000_2019['Date'] = pd.to_datetime(

      Date  Gold_Price
0  2000-01     4510.75
1  2000-02     4712.25
2  2000-03     4541.90
3  2000-04     4462.06
4  2000-05     4371.14

In [118]:
df_bombay_gp_2000_2019

        Date  Gold_Price
0    2000-01     4510.75
1    2000-02     4712.25
2    2000-03     4541.90
3    2000-04     4462.06
4    2000-05     4371.14
..       ...         ...
235  2019-08    36745.24
236  2019-09    37484.21
237  2019-10    38005.56
238  2019-11    38718.50
239  2019-12    38695.24

[240 rows x 2 columns]

In [119]:
df_gold_price_master = pd.concat([
    df_bombay_gp_2000_2019,
        df_gp_2020,
        df_gp_2021,
        df_gp_2022,
        df_gp_2023,
        df_gp_2024,
        df_gp_2025,
        df_gp_2026
],
    axis=0,
    ignore_index=True
)

In [120]:
df_gold_price_master

        Date  Gold_Price
0    2000-01     4510.75
1    2000-02     4712.25
2    2000-03     4541.90
3    2000-04     4462.06
4    2000-05     4371.14
..       ...         ...
307  2025-10   122294.30
308  2025-11   122834.00
309  2025-12   131322.55
310  2026-01   146169.80
311  2026-02   154370.40

[312 rows x 2 columns]

In [121]:
full_dates = pd.period_range(
    start='2000-01',
    end='2026-03',
    freq='M'
).astype(str)

missing_dates = set(full_dates) - set(df_gold_price_master['Date'])

missing_dates

{'2020-04', '2020-05', '2026-03'}

In [122]:
missing_rows = pd.DataFrame({
    'Date': ['2020-04', '2020-05', '2026-03'],
    'Gold_Price': [48723.22, 48723.22, 147395]
})

df_gold_price_master = pd.concat(
    [df_gold_price_master, missing_rows],
    ignore_index=True
)

df_gold_price_master = (
    df_gold_price_master
    .sort_values('Date')
)

df_gold_price_master.reset_index(
    drop=True,
    inplace=True
)

df_gold_price_master

        Date  Gold_Price
0    2000-01     4510.75
1    2000-02     4712.25
2    2000-03     4541.90
3    2000-04     4462.06
4    2000-05     4371.14
..       ...         ...
310  2025-11   122834.00
311  2025-12   131322.55
312  2026-01   146169.80
313  2026-02   154370.40
314  2026-03   147395.00

[315 rows x 2 columns]

In [123]:
df_gold_price_master.to_excel(
    'clean_gold_price.xlsx',
    index=False
)

In [124]:
df_gold_master = pd.merge(
    df_gold_price_master,
    df_gold_reservs,
    on='Date',
    how='outer'
)

In [125]:
df_gold_master = pd.merge(
    df_gold_master,
    df_gold_volume,
    on='Date',
    how='outer'
)

In [126]:
df_gold_master = (
    df_gold_master
    .sort_values('Date')
)

In [127]:
df_gold_master.reset_index(
    drop=True,
    inplace=True
)

In [128]:
df_gold_master

        Date  Gold_Price  Gold_Reservs_USD_mn  Gold_Volume_mn_troy_oz
0    2000-01     4510.75               2945.0               11.502339
1    2000-02     4712.25               3104.0               11.502339
2    2000-03     4541.90               2974.0               11.502339
3    2000-04     4462.06               2895.0               11.502339
4    2000-05     4371.14               2851.0               11.502339
..       ...         ...                  ...                     ...
310  2025-11   122834.00             106740.0               28.298487
311  2025-12   131322.55             111262.0               28.303688
312  2026-01   146169.80             126904.0               28.303707
313  2026-02   154370.40             131630.0               28.303709
314  2026-03   147395.00             115395.0               28.309308

[315 rows x 4 columns]

In [129]:
df_gold_master['Gold_Price[/10gm]'] = df_gold_master['Gold_Price']

In [132]:
df_gold_master = df_gold_master.drop(columns = ['Gold_Price'])

In [133]:
df_gold_master.to_excel(
    'clean_gold_master.xlsx',
    index=False
)