<a href="https://colab.research.google.com/github/UKD1211/Macroeconomic_impact_of_gold-_Econ_growth/blob/main/Research_proj_TSA_data.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
import numpy as np

In [2]:
df_gold_reservs = pd.read_excel("/content/Gold Reserves USD mn Monthly India.xlsx")

In [3]:
df_gold_reservs

              Unnamed: 0 Gold Reserves: USD mn: Monthly: India
0                 Region                                 India
1            Subnational                                   NaN
2              Frequency                               Monthly
3                   Unit                                USD mn
4                 Source                             CEIC Data
..                   ...                                   ...
855  2025-11-01 00:00:00                                106740
856  2025-12-01 00:00:00                                111262
857  2026-01-01 00:00:00                                126904
858  2026-02-01 00:00:00                                131630
859  2026-03-01 00:00:00                                115395

[860 rows x 2 columns]

In [4]:
df_gold_reservs.columns = ["Date", "Gold_Reservs_USD_mn"]

In [5]:
df_gold_reservs

                    Date Gold_Reservs_USD_mn
0                 Region               India
1            Subnational                 NaN
2              Frequency             Monthly
3                   Unit              USD mn
4                 Source           CEIC Data
..                   ...                 ...
855  2025-11-01 00:00:00              106740
856  2025-12-01 00:00:00              111262
857  2026-01-01 00:00:00              126904
858  2026-02-01 00:00:00              131630
859  2026-03-01 00:00:00              115395

[860 rows x 2 columns]

In [10]:
df_gold_reservs = df_gold_reservs.copy()

df_gold_reservs['Date'] = pd.to_datetime(
    df_gold_reservs['Date'],
    errors='coerce'
)

df_gold_reservs = df_gold_reservs[
    df_gold_reservs['Date'].notna()
]

df_gold_reservs['Gold_Reservs_USD_mn'] = pd.to_numeric(
    df_gold_reservs['Gold_Reservs_USD_mn'],
    errors='coerce'
)

df_gold_reservs = df_gold_reservs[
    df_gold_reservs['Date'] >= '2000-01-01'
]

df_gold_reservs.reset_index(drop=True, inplace=True)

In [15]:
df_gold_reservs

          Date  Gold_Reservs_USD_mn
0   2000-01-01               2945.0
1   2000-02-01               3104.0
2   2000-03-01               2974.0
3   2000-04-01               2895.0
4   2000-05-01               2851.0
..         ...                  ...
310 2025-11-01             106740.0
311 2025-12-01             111262.0
312 2026-01-01             126904.0
313 2026-02-01             131630.0
314 2026-03-01             115395.0

[315 rows x 2 columns]

In [16]:
df_gold_reservs.describe()

                                Date  Gold_Reservs_USD_mn
count                            315           315.000000
mean   2013-01-30 09:13:08.571428608         23261.104943
min              2000-01-01 00:00:00          2695.000000
25%              2006-07-16 12:00:00          6397.500000
50%              2013-02-01 00:00:00         20183.200000
75%              2019-08-16 12:00:00         28130.500000
max              2026-03-01 00:00:00        131630.000000
std                              NaN         22057.399171

In [20]:
!pip install openpyxl
df_gold_reservs.to_excel(
    'clean_gold_reserves.xlsx',
    index=False
)

Requirement already satisfied: openpyxl in /usr/local/lib/python3.12/dist-packages (3.1.5)
Requirement already satisfied: et-xmlfile in /usr/local/lib/python3.12/dist-packages (from openpyxl) (2.0.0)

In [21]:
df_gold_volume = pd.read_excel("/content/International Liquidity Gold Volume.xlsx")

In [22]:
df_gold_volume

              Unnamed: 0 International Liquidity: Gold: Volume
0                 Region                                 India
1            Subnational                                   NaN
2              Frequency                               Monthly
3                   Unit                       Fine Troy oz mn
4                 Source           International Monetary Fund
..                   ...                                   ...
861  2025-11-01 00:00:00                             28.298487
862  2025-12-01 00:00:00                             28.303688
863  2026-01-01 00:00:00                             28.303707
864  2026-02-01 00:00:00                             28.303709
865  2026-03-01 00:00:00                             28.309308

[866 rows x 2 columns]

In [23]:
# Rename columns
df_gold_volume.columns = ['Date', 'Gold_Volume_mn_troy_oz']

# Convert Date column
df_gold_volume['Date'] = pd.to_datetime(
    df_gold_volume['Date'],
    errors='coerce'
)

# Keep only valid date rows
df_gold_volume = df_gold_volume[
    df_gold_volume['Date'].notna()
]

# Convert gold volume column to numeric
df_gold_volume['Gold_Volume_mn_troy_oz'] = pd.to_numeric(
    df_gold_volume['Gold_Volume_mn_troy_oz'],
    errors='coerce'
)

# Keep only data from 2000 onwards
df_gold_volume = df_gold_volume[
    df_gold_volume['Date'] >= '2000-01-01'
]

# Reset index
df_gold_volume.reset_index(drop=True, inplace=True)

# Preview cleaned dataframe
df_gold_volume.head()

/tmp/ipykernel_14993/2340691387.py:5: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  df_gold_volume['Date'] = pd.to_datetime(
/tmp/ipykernel_14993/2340691387.py:16: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_gold_volume['Gold_Volume_mn_troy_oz'] = pd.to_numeric(

        Date  Gold_Volume_mn_troy_oz
0 2000-01-01               11.502339
1 2000-02-01               11.502339
2 2000-03-01               11.502339
3 2000-04-01               11.502339
4 2000-05-01               11.502339

In [24]:
df_gold_volume

          Date  Gold_Volume_mn_troy_oz
0   2000-01-01               11.502339
1   2000-02-01               11.502339
2   2000-03-01               11.502339
3   2000-04-01               11.502339
4   2000-05-01               11.502339
..         ...                     ...
310 2025-11-01               28.298487
311 2025-12-01               28.303688
312 2026-01-01               28.303707
313 2026-02-01               28.303709
314 2026-03-01               28.309308

[315 rows x 2 columns]

In [25]:
df_gold_volume.to_excel(
    'clean_gold_volume.xlsx',
    index=False
)