<a href="https://colab.research.google.com/github/UKD1211/Macroeconomic_impact_of_gold-_Econ_growth/blob/main/research_TSA_master_dataset_prep.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [242]:
import pandas as pd
import numpy as np

In [243]:
df_gold_master = pd.read_excel("/content/clean_gold_master.xlsx")

In [244]:
df_gold_master

        Date  Gold_Reservs_USD_mn  Gold_Volume_mn_troy_oz  Gold_Price[/10gm]
0    2000-01               2945.0               11.502339            4510.75
1    2000-02               3104.0               11.502339            4712.25
2    2000-03               2974.0               11.502339            4541.90
3    2000-04               2895.0               11.502339            4462.06
4    2000-05               2851.0               11.502339            4371.14
..       ...                  ...                     ...                ...
310  2025-11             106740.0               28.298487          122834.00
311  2025-12             111262.0               28.303688          131322.55
312  2026-01             126904.0               28.303707          146169.80
313  2026-02             131630.0               28.303709          154370.40
314  2026-03             115395.0               28.309308          147395.00

[315 rows x 4 columns]

In [245]:
df_cpi_11_14_gold = pd.read_excel("/content/CPIndex_Jan11-To-Dec14_gold.xlsx")

In [246]:
df_cpi_11_14_gold

    Year      Month  Item-Code Description  Combined Index
0   2011    January     506181        gold           111.7
1   2011   February     506181        gold           111.7
2   2011      March     506181        gold           114.3
3   2011      April     506181        gold           117.3
4   2011        May     506181        gold           120.3
5   2011       June     506181        gold           122.0
6   2011       July     506181        gold           123.8
7   2011     August     506181        gold           141.2
8   2011  September     506181        gold           147.4
9   2011    October     506181        gold           146.3
10  2011   November     506181        gold           154.3
11  2011   December     506181        gold           153.7
12  2012    January     506181        gold           151.0
13  2012   February     506181        gold           152.5
14  2012      March     506181        gold           152.3
15  2012      April     506181        gold           154.9
16  2012        May     506181        gold           157.0
17  2012       June     506181        gold           161.6
18  2012       July     506181        gold           160.9
19  2012     August     506181        gold           163.5
20  2012  September     506181        gold           171.5
21  2012    October     506181        gold           169.4
22  2012   November     506181        gold           170.9
23  2012   December     506181        gold           169.5
24  2013    January     506181        gold           167.9
25  2013   February     506181        gold           165.4
26  2013      March     506181        gold           162.5
27  2013      April     506181        gold           153.5
28  2013        May     506181        gold           148.3
29  2013       June     506181        gold           149.1
30  2013       July     506181        gold           146.3
31  2013     August     506181        gold           158.5
32  2013  September     506181        gold           163.4
33  2013    October     506181        gold           164.5
34  2013   November     506181        gold           165.9
35  2013   December     506181        gold           163.0
36  2014    January     506181        gold           161.8
37  2014   February     506181        gold           163.4
38  2014      March     506181        gold           163.0
39  2014      April     506181        gold           161.0
40  2014        May     506181        gold           159.6
41  2014       June     506181        gold           152.0
42  2014       July     506181        gold           153.1
43  2014     August     506181        gold           153.9
44  2014  September     506181        gold           149.6
45  2014    October     506181        gold           148.6
46  2014   November     506181        gold           144.3
47  2014   December     506181        gold           146.0

In [247]:
df_cpi_15_25_gold = pd.read_excel("/content/CPIndex_Jan15-To-Dec25_gold.xlsx")

In [248]:
df_cpi_15_25_gold

,All India Item Combined Index (Base 2012=100),Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4
0,Year,Month,Item-Code,Description,Combined Index
1,2015,January,6.1.06.2.1.01.0,gold,93.2
2,2015,February,6.1.06.2.1.01.0,gold,92.9
3,2015,March,6.1.06.2.1.01.0,gold,90.9
4,2015,April,6.1.06.2.1.01.0,gold,91.7
...,...,...,...,...,...
125,2025,August,6.1.06.2.1.01.0,gold,333.2
126,2025,September,6.1.06.2.1.01.0,gold,359.4
127,2025,October,6.1.06.2.1.01.0,gold,404.2
128,2025,November,6.1.06.2.1.01.0,gold,408.4
129,2025,December,6.1.06.2.1.01.0,gold,433.9

In [249]:
df_inr_usd = pd.read_csv("/content/INR_USD_conversion_rates.csv")

In [250]:
df_inr_usd

     observation_date  DEXINUS
0          2000-01-03    43.55
1          2000-01-04    43.55
2          2000-01-05    43.55
3          2000-01-06    43.55
4          2000-01-07    43.55
...               ...      ...
6880       2026-05-18    96.35
6881       2026-05-19    96.53
6882       2026-05-20    96.82
6883       2026-05-21    96.20
6884       2026-05-22    95.69

[6885 rows x 2 columns]

In [251]:
df_repo_rate = pd.read_excel("/content/Policy Rate Month End India Repo Rate(2).xlsx")

In [252]:
df_repo_rate

              Unnamed: 0 Policy Rate: Month End: India: Repo Rate
0                 Region                                    India
1            Subnational                                      NaN
2              Frequency                                  Monthly
3                   Unit                                     % pa
4                 Source                                CEIC Data
..                   ...                                      ...
324  2025-12-01 00:00:00                                     5.25
325  2026-01-01 00:00:00                                     5.25
326  2026-02-01 00:00:00                                     5.25
327  2026-03-01 00:00:00                                     5.25
328  2026-04-01 00:00:00                                     5.25

[329 rows x 2 columns]

In [253]:
month_map = {
    'January':'01',
    'February':'02',
    'March':'03',
    'April':'04',
    'May':'05',
    'June':'06',
    'July':'07',
    'August':'08',
    'September':'09',
    'October':'10',
    'November':'11',
    'December':'12'
}

df_cpi_11_14_gold['Date'] = (
    df_cpi_11_14_gold['Year'].astype(str)
    + '-'
    + df_cpi_11_14_gold['Month'].map(month_map)
)

df_cpi_11_14_gold = df_cpi_11_14_gold[
    ['Date','Combined Index']
]

df_cpi_11_14_gold.columns = [
    'Date',
    'Gold_CPI'
]

In [254]:
df_cpi_15_25_gold.columns = [
    'Year',
    'Month',
    'Item_Code',
    'Description',
    'Gold_CPI'
]

df_cpi_15_25_gold['Date'] = (
    df_cpi_15_25_gold['Year'].astype(str)
    + '-'
    + df_cpi_15_25_gold['Month'].map(month_map)
)

df_cpi_15_25_gold = df_cpi_15_25_gold[
    ['Date','Gold_CPI']
]

In [255]:
df_gold_cpi = pd.concat(
    [
        df_cpi_11_14_gold,
        df_cpi_15_25_gold
    ],
    ignore_index=True
)

df_gold_cpi = (
    df_gold_cpi
    .sort_values('Date')
    .reset_index(drop=True)
)

In [256]:
df_gold_cpi

        Date        Gold_CPI
0    2011-01           111.7
1    2011-02           111.7
2    2011-03           114.3
3    2011-04           117.3
4    2011-05           120.3
..       ...             ...
173  2025-09           359.4
174  2025-10           404.2
175  2025-11           408.4
176  2025-12           433.9
177      NaN  Combined Index

[178 rows x 2 columns]

In [257]:
df_gold_master = pd.merge(
    df_gold_master,
    df_gold_cpi,
    on='Date',
    how='left'
)

In [258]:
df_gold_master

,Date,Gold_Reservs_USD_mn,Gold_Volume_mn_troy_oz,Gold_Price[/10gm],Gold_CPI
0,2000-01,2945.0,11.502339,4510.75,NaN
1,2000-02,3104.0,11.502339,4712.25,NaN
2,2000-03,2974.0,11.502339,4541.90,NaN
3,2000-04,2895.0,11.502339,4462.06,NaN
4,2000-05,2851.0,11.502339,4371.14,NaN
...,...,...,...,...,...
310,2025-11,106740.0,28.298487,122834.00,408.4
311,2025-12,111262.0,28.303688,131322.55,433.9
312,2026-01,126904.0,28.303707,146169.80,NaN
313,2026-02,131630.0,28.303709,154370.40,NaN
314,2026-03,115395.0,28.309308,147395.00,NaN

In [259]:
df_gold_master['Gold_CPI'] = (
    df_gold_master['Gold_CPI']
    .fillna('---')
)

In [260]:
df_gold_master_with_cpi = df_gold_master.copy()

In [261]:
df_gold_master_with_cpi.to_excel(
    "gold_master_dataset_with_cpi.xlsx",
    index=False
)

In [262]:
# Rename columns
df_inr_usd.columns = ['Date', 'USDINR']

# Convert Date column
df_inr_usd['Date'] = pd.to_datetime(
    df_inr_usd['Date'],
    errors='coerce'
)

# Convert exchange rate to numeric
df_inr_usd['USDINR'] = pd.to_numeric(
    df_inr_usd['USDINR'],
    errors='coerce'
)

# Remove invalid rows
df_inr_usd = df_inr_usd.dropna()

# Convert date to Year-Month
df_inr_usd['Date'] = (
    df_inr_usd['Date']
    .dt.strftime('%Y-%m')
)

# Monthly average
df_inr_usd = (
    df_inr_usd
    .groupby('Date', as_index=False)
    ['USDINR']
    .mean()
)

# Round values
df_inr_usd['USDINR'] = (
    df_inr_usd['USDINR']
    .round(2)
)

# Sort
df_inr_usd = (
    df_inr_usd
    .sort_values('Date')
    .reset_index(drop=True)
)

df_inr_usd.head()

/tmp/ipykernel_1043/3790533072.py:20: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_inr_usd['Date'] = (

      Date  USDINR
0  2000-01   43.59
1  2000-02   43.65
2  2000-03   43.64
3  2000-04   43.68
4  2000-05   44.08

In [263]:
df_inr_usd

        Date  USDINR
0    2000-01   43.59
1    2000-02   43.65
2    2000-03   43.64
3    2000-04   43.68
4    2000-05   44.08
..       ...     ...
312  2026-01   90.90
313  2026-02   90.75
314  2026-03   92.82
315  2026-04   93.48
316  2026-05   95.54

[317 rows x 2 columns]

In [264]:
df_master = pd.merge(
    df_gold_master,
    df_inr_usd,
    on='Date',
    how='left'
)

In [265]:
df_master

,Date,Gold_Reservs_USD_mn,Gold_Volume_mn_troy_oz,Gold_Price[/10gm],Gold_CPI,USDINR
0,2000-01,2945.0,11.502339,4510.75,---,43.59
1,2000-02,3104.0,11.502339,4712.25,---,43.65
2,2000-03,2974.0,11.502339,4541.90,---,43.64
3,2000-04,2895.0,11.502339,4462.06,---,43.68
4,2000-05,2851.0,11.502339,4371.14,---,44.08
...,...,...,...,...,...,...
310,2025-11,106740.0,28.298487,122834.00,408.4,88.84
311,2025-12,111262.0,28.303688,131322.55,433.9,90.04
312,2026-01,126904.0,28.303707,146169.80,---,90.90
313,2026-02,131630.0,28.303709,154370.40,---,90.75
314,2026-03,115395.0,28.309308,147395.00,---,92.82

In [266]:
# Rename columns
df_repo_rate.columns = ['Date', 'Repo_Rate']

# Convert Date
df_repo_rate['Date'] = pd.to_datetime(
    df_repo_rate['Date'],
    errors='coerce'
)

# Keep only valid date rows
df_repo_rate = df_repo_rate[
    df_repo_rate['Date'].notna()
]

# Convert repo rate to numeric
df_repo_rate['Repo_Rate'] = pd.to_numeric(
    df_repo_rate['Repo_Rate'],
    errors='coerce'
)

# Keep from 2000 onward
df_repo_rate = df_repo_rate[
    df_repo_rate['Date'] >= '2000-01-01'
]

# Convert to YYYY-MM
df_repo_rate['Date'] = (
    df_repo_rate['Date']
    .dt.strftime('%Y-%m')
)

# Sort
df_repo_rate = (
    df_repo_rate
    .sort_values('Date')
    .reset_index(drop=True)
)

df_repo_rate.head()

/tmp/ipykernel_1043/756264131.py:5: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  df_repo_rate['Date'] = pd.to_datetime(
/tmp/ipykernel_1043/756264131.py:16: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_repo_rate['Repo_Rate'] = pd.to_numeric(

      Date  Repo_Rate
0  2001-04       8.75
1  2001-05       8.75
2  2001-06       8.50
3  2001-07       8.50
4  2001-08       8.50

In [267]:
df_repo_rate

        Date  Repo_Rate
0    2001-04       8.75
1    2001-05       8.75
2    2001-06       8.50
3    2001-07       8.50
4    2001-08       8.50
..       ...        ...
296  2025-12       5.25
297  2026-01       5.25
298  2026-02       5.25
299  2026-03       5.25
300  2026-04       5.25

[301 rows x 2 columns]

In [268]:
df_master = pd.merge(
    df_master,
    df_repo_rate,
    on='Date',
    how='left'
)

In [269]:
df_master['Repo_Rate'] = (
    df_master['Repo_Rate']
    .fillna('---')
)

In [270]:
df_master

,Date,Gold_Reservs_USD_mn,Gold_Volume_mn_troy_oz,Gold_Price[/10gm],Gold_CPI,USDINR,Repo_Rate
0,2000-01,2945.0,11.502339,4510.75,---,43.59,---
1,2000-02,3104.0,11.502339,4712.25,---,43.65,---
2,2000-03,2974.0,11.502339,4541.90,---,43.64,---
3,2000-04,2895.0,11.502339,4462.06,---,43.68,---
4,2000-05,2851.0,11.502339,4371.14,---,44.08,---
...,...,...,...,...,...,...,...
310,2025-11,106740.0,28.298487,122834.00,408.4,88.84,5.5
311,2025-12,111262.0,28.303688,131322.55,433.9,90.04,5.25
312,2026-01,126904.0,28.303707,146169.80,---,90.90,5.25
313,2026-02,131630.0,28.303709,154370.40,---,90.75,5.25
314,2026-03,115395.0,28.309308,147395.00,---,92.82,5.25

In [271]:
df_cpi_overall_13_25 = pd.read_csv("/content/CPIndex_overall_2013-To-2025.csv")

In [272]:
df_cpi_overall_13_25

                                                                                                                   Combined CPI (Base 2012=100)
Year State     Description                Jan   Feb   Mar   Apr   May   Jun   Jul   Aug   Sep   Oct   Nov   Dec                             NaN
2013 ALL India General Index (All Groups) 104.6 105.3 105.5 106.1 106.9 109.3 111.0 112.4 113.7 114.8 116.3 114.5                           NaN
2014 ALL India General Index (All Groups) 113.6 113.6 114.2 115.1 115.8 116.7 119.2 120.3 120.1 120.1 120.1 119.4                           NaN
2015 ALL India General Index (All Groups) 119.5 119.7 120.2 120.7 121.6 123.0 123.6 124.8 125.4 126.1 126.6 126.1                           NaN
2016 ALL India General Index (All Groups) 126.3 126.0 126.0 127.3 128.6 130.1 131.1 131.1 130.9 131.4 131.2 130.4                           NaN
2017 ALL India General Index (All Groups) 130.3 130.6 130.9 131.1 131.4 132.0 134.2 135.4 135.2 136.1 137.6 137.2                           NaN
2018 ALL India General Index (All Groups) 136.9 136.4 136.5 137.1 137.8 138.5 139.8 140.4 140.2 140.7 140.8 140.1                           NaN
2019 ALL India General Index (All Groups) 139.6 139.9 140.4 141.2 142.0 142.9 144.2 145.0 145.8 147.2 148.6 150.4                           NaN
2020 ALL India General Index (All Groups) 150.2 149.1 148.6 151.4 150.9 151.8 153.9 154.7 156.4 158.4 158.9 157.3                           NaN
2021 ALL India General Index (All Groups) 156.3 156.6 156.8 157.8 160.4 161.3 162.5 162.9 163.2 165.5 166.7 166.2                           NaN
2022 ALL India General Index (All Groups) 165.7 166.1 167.7 170.1 171.7 172.6 173.4 174.3 175.3 176.7 176.5 175.7                           NaN
2023 ALL India General Index (All Groups) 176.5 176.8 177.2 178.1 179.1 181.0 186.3 186.2 184.1 185.3 186.3 185.7                           NaN
2024 ALL India General Index (All Groups) 185.5 185.8 185.8 186.7 187.7 190.2 193.0 193.0 194.2 196.8 196.5 195.4                           NaN
2025 ALL India General Index (All Groups) 193.4 192.5 192.0 192.6 193.0 194.2 196.1 197.0 197.0 197.3 197.9 198.0                           NaN

In [273]:
df_cpi_overall_13_25.columns

Index(['Combined CPI (Base 2012=100)'], dtype='object')

In [274]:
print(df_cpi_overall_13_25.columns.tolist())

['Combined CPI (Base 2012=100)']

In [275]:
df_cpi_overall_13_25.head()

                                                                                                                   Combined CPI (Base 2012=100)
Year State     Description                Jan   Feb   Mar   Apr   May   Jun   Jul   Aug   Sep   Oct   Nov   Dec                             NaN
2013 ALL India General Index (All Groups) 104.6 105.3 105.5 106.1 106.9 109.3 111.0 112.4 113.7 114.8 116.3 114.5                           NaN
2014 ALL India General Index (All Groups) 113.6 113.6 114.2 115.1 115.8 116.7 119.2 120.3 120.1 120.1 120.1 119.4                           NaN
2015 ALL India General Index (All Groups) 119.5 119.7 120.2 120.7 121.6 123.0 123.6 124.8 125.4 126.1 126.6 126.1                           NaN
2016 ALL India General Index (All Groups) 126.3 126.0 126.0 127.3 128.6 130.1 131.1 131.1 130.9 131.4 131.2 130.4                           NaN

In [276]:
print(df_cpi_overall_13_25.shape)

df_cpi_overall_13_25.head(5)

(14, 1)

                                                                                                                   Combined CPI (Base 2012=100)
Year State     Description                Jan   Feb   Mar   Apr   May   Jun   Jul   Aug   Sep   Oct   Nov   Dec                             NaN
2013 ALL India General Index (All Groups) 104.6 105.3 105.5 106.1 106.9 109.3 111.0 112.4 113.7 114.8 116.3 114.5                           NaN
2014 ALL India General Index (All Groups) 113.6 113.6 114.2 115.1 115.8 116.7 119.2 120.3 120.1 120.1 120.1 119.4                           NaN
2015 ALL India General Index (All Groups) 119.5 119.7 120.2 120.7 121.6 123.0 123.6 124.8 125.4 126.1 126.6 126.1                           NaN
2016 ALL India General Index (All Groups) 126.3 126.0 126.0 127.3 128.6 130.1 131.1 131.1 130.9 131.4 131.2 130.4                           NaN

In [277]:
df_cpi_overall_13_25.columns = [
    col[1] if isinstance(col, tuple) else col
    for col in df_cpi_overall_13_25.columns
]

In [278]:
print(df_cpi_overall_13_25.columns.tolist())

['Combined CPI (Base 2012=100)']

In [279]:
type(df_cpi_overall_13_25.iloc[0,0])

numpy.float64

In [280]:
df_cpi_overall_13_25.iloc[0,0]

np.float64(nan)

In [281]:
df_cpi_overall_13_25.head(3).to_dict()

{'Combined CPI (Base 2012=100)': {('Year',
   'State',
   'Description',
   'Jan',
   'Feb',
   'Mar',
   'Apr',
   'May',
   'Jun',
   'Jul',
   'Aug',
   'Sep',
   'Oct',
   'Nov',
   'Dec'): nan,
  ('2013',
   'ALL India',
   'General Index (All Groups)',
   '104.6',
   '105.3',
   '105.5',
   '106.1',
   '106.9',
   '109.3',
   '111.0',
   '112.4',
   '113.7',
   '114.8',
   '116.3',
   '114.5'): nan,
  ('2014',
   'ALL India',
   'General Index (All Groups)',
   '113.6',
   '113.6',
   '114.2',
   '115.1',
   '115.8',
   '116.7',
   '119.2',
   '120.3',
   '120.1',
   '120.1',
   '120.1',
   '119.4'): nan}}

In [282]:
print(df_cpi_overall_13_25.index)

MultiIndex([('Year',     'State',                'Description',   'Jan', ...),
            ('2013', 'ALL India', 'General Index (All Groups)', '104.6', ...),
            ('2014', 'ALL India', 'General Index (All Groups)', '113.6', ...),
            ('2015', 'ALL India', 'General Index (All Groups)', '119.5', ...),
            ('2016', 'ALL India', 'General Index (All Groups)', '126.3', ...),
            ('2017', 'ALL India', 'General Index (All Groups)', '130.3', ...),
            ('2018', 'ALL India', 'General Index (All Groups)', '136.9', ...),
            ('2019', 'ALL India', 'General Index (All Groups)', '139.6', ...),
            ('2020', 'ALL India', 'General Index (All Groups)', '150.2', ...),
            ('2021', 'ALL India', 'General Index (All Groups)', '156.3', ...),
            ('2022', 'ALL India', 'General Index (All Groups)', '165.7', ...),
            ('2023', 'ALL India', 'General Index (All Groups)', '176.5', ...),
            ('2024', 'ALL India', 'General Index (All Groups)', '185.5', ...),
            ('2025', 'ALL India', 'General Index (All Groups)', '193.4', ...)],
           )

In [283]:
# Convert MultiIndex to dataframe
df_cpi_overall_master = pd.DataFrame(
    df_cpi_overall_13_25.index.tolist()
)

# Use first row as column names
df_cpi_overall_master.columns = df_cpi_overall_master.iloc[0]

# Remove header row
df_cpi_overall_master = df_cpi_overall_master.iloc[1:]

# Reset index
df_cpi_overall_master = df_cpi_overall_master.reset_index(drop=True)

df_cpi_overall_master.head()

,Year,State,Description,Jan,Feb,Mar,Apr,May,Jun,Jul,Aug,Sep,Oct,Nov,Dec
0,2013,ALL India,General Index (All Groups),104.6,105.3,105.5,106.1,106.9,109.3,111.0,112.4,113.7,114.8,116.3,114.5
1,2014,ALL India,General Index (All Groups),113.6,113.6,114.2,115.1,115.8,116.7,119.2,120.3,120.1,120.1,120.1,119.4
2,2015,ALL India,General Index (All Groups),119.5,119.7,120.2,120.7,121.6,123.0,123.6,124.8,125.4,126.1,126.6,126.1
3,2016,ALL India,General Index (All Groups),126.3,126.0,126.0,127.3,128.6,130.1,131.1,131.1,130.9,131.4,131.2,130.4
4,2017,ALL India,General Index (All Groups),130.3,130.6,130.9,131.1,131.4,132.0,134.2,135.4,135.2,136.1,137.6,137.2

In [284]:
month_cols = [
    'Jan','Feb','Mar','Apr','May','Jun',
    'Jul','Aug','Sep','Oct','Nov','Dec'
]

df_cpi_overall_master = df_cpi_overall_master.melt(
    id_vars='Year',
    value_vars=month_cols,
    var_name='Month',
    value_name='Overall_CPI'
)

In [285]:
month_map = {
    'Jan':'01',
    'Feb':'02',
    'Mar':'03',
    'Apr':'04',
    'May':'05',
    'Jun':'06',
    'Jul':'07',
    'Aug':'08',
    'Sep':'09',
    'Oct':'10',
    'Nov':'11',
    'Dec':'12'
}

df_cpi_overall_master['Date'] = (
    df_cpi_overall_master['Year'].astype(str)
    + '-'
    + df_cpi_overall_master['Month'].map(month_map)
)

df_cpi_overall_master = (
    df_cpi_overall_master[['Date','Overall_CPI']]
    .sort_values('Date')
    .reset_index(drop=True)
)

In [286]:
df_cpi_overall_master

        Date Overall_CPI
0    2013-01       104.6
1    2013-02       105.3
2    2013-03       105.5
3    2013-04       106.1
4    2013-05       106.9
..       ...         ...
151  2025-08       197.0
152  2025-09       197.0
153  2025-10       197.3
154  2025-11       197.9
155  2025-12       198.0

[156 rows x 2 columns]

In [287]:
df_cpi_overall_master.shape

(156, 2)

In [288]:
df_cpi_overall_master.to_excel(
    "cpi_overall_master.xlsx",
    index=False
)

In [289]:
df_master = pd.merge(
    df_master,
    df_cpi_overall_master,
    on='Date',
    how='left'
)

In [290]:
df_master

,Date,Gold_Reservs_USD_mn,Gold_Volume_mn_troy_oz,Gold_Price[/10gm],Gold_CPI,USDINR,Repo_Rate,Overall_CPI
0,2000-01,2945.0,11.502339,4510.75,---,43.59,---,NaN
1,2000-02,3104.0,11.502339,4712.25,---,43.65,---,NaN
2,2000-03,2974.0,11.502339,4541.90,---,43.64,---,NaN
3,2000-04,2895.0,11.502339,4462.06,---,43.68,---,NaN
4,2000-05,2851.0,11.502339,4371.14,---,44.08,---,NaN
...,...,...,...,...,...,...,...,...
310,2025-11,106740.0,28.298487,122834.00,408.4,88.84,5.5,197.9
311,2025-12,111262.0,28.303688,131322.55,433.9,90.04,5.25,198.0
312,2026-01,126904.0,28.303707,146169.80,---,90.90,5.25,NaN
313,2026-02,131630.0,28.303709,154370.40,---,90.75,5.25,NaN
314,2026-03,115395.0,28.309308,147395.00,---,92.82,5.25,NaN

In [291]:
df_master['Overall_CPI'] = df_master['Overall_CPI'].fillna("---")

In [292]:
df_master

,Date,Gold_Reservs_USD_mn,Gold_Volume_mn_troy_oz,Gold_Price[/10gm],Gold_CPI,USDINR,Repo_Rate,Overall_CPI
0,2000-01,2945.0,11.502339,4510.75,---,43.59,---,---
1,2000-02,3104.0,11.502339,4712.25,---,43.65,---,---
2,2000-03,2974.0,11.502339,4541.90,---,43.64,---,---
3,2000-04,2895.0,11.502339,4462.06,---,43.68,---,---
4,2000-05,2851.0,11.502339,4371.14,---,44.08,---,---
...,...,...,...,...,...,...,...,...
310,2025-11,106740.0,28.298487,122834.00,408.4,88.84,5.5,197.9
311,2025-12,111262.0,28.303688,131322.55,433.9,90.04,5.25,198.0
312,2026-01,126904.0,28.303707,146169.80,---,90.90,5.25,---
313,2026-02,131630.0,28.303709,154370.40,---,90.75,5.25,---
314,2026-03,115395.0,28.309308,147395.00,---,92.82,5.25,---

In [293]:
import numpy as np
import pandas as pd

# Convert Overall_CPI to numeric just in case
df_master['Overall_CPI'] = pd.to_numeric(
    df_master['Overall_CPI'],
    errors='coerce'
)

# Year-on-Year Inflation (%)
df_master['Inflation_YoY'] = (
    df_master['Overall_CPI']
    .pct_change(periods=12)
    * 100
)

# Month-on-Month Inflation (%)
df_master['Inflation_MoM'] = (
    df_master['Overall_CPI']
    .pct_change(periods=1)
    * 100
)

# Round values
df_master['Inflation_YoY'] = (
    df_master['Inflation_YoY']
    .round(2)
)

df_master['Inflation_MoM'] = (
    df_master['Inflation_MoM']
    .round(2)
)

# Optional: replace NaN with '---' for display/reporting
df_master['Inflation_YoY'] = (
    df_master['Inflation_YoY']
    .fillna('---')
)

df_master['Inflation_MoM'] = (
    df_master['Inflation_MoM']
    .fillna('---')
)

df_master.head()

/tmp/ipykernel_1043/1521117497.py:13: FutureWarning: The default fill_method='pad' in Series.pct_change is deprecated and will be removed in a future version. Either fill in any non-leading NA values prior to calling pct_change or specify 'fill_method=None' to not fill NA values.
  .pct_change(periods=12)
/tmp/ipykernel_1043/1521117497.py:20: FutureWarning: The default fill_method='pad' in Series.pct_change is deprecated and will be removed in a future version. Either fill in any non-leading NA values prior to calling pct_change or specify 'fill_method=None' to not fill NA values.
  .pct_change(periods=1)

,Date,Gold_Reservs_USD_mn,Gold_Volume_mn_troy_oz,Gold_Price[/10gm],Gold_CPI,USDINR,Repo_Rate,Overall_CPI,Inflation_YoY,Inflation_MoM
0,2000-01,2945.0,11.502339,4510.75,---,43.59,---,NaN,---,---
1,2000-02,3104.0,11.502339,4712.25,---,43.65,---,NaN,---,---
2,2000-03,2974.0,11.502339,4541.90,---,43.64,---,NaN,---,---
3,2000-04,2895.0,11.502339,4462.06,---,43.68,---,NaN,---,---
4,2000-05,2851.0,11.502339,4371.14,---,44.08,---,NaN,---,---

In [294]:
df_master

,Date,Gold_Reservs_USD_mn,Gold_Volume_mn_troy_oz,Gold_Price[/10gm],Gold_CPI,USDINR,Repo_Rate,Overall_CPI,Inflation_YoY,Inflation_MoM
0,2000-01,2945.0,11.502339,4510.75,---,43.59,---,NaN,---,---
1,2000-02,3104.0,11.502339,4712.25,---,43.65,---,NaN,---,---
2,2000-03,2974.0,11.502339,4541.90,---,43.64,---,NaN,---,---
3,2000-04,2895.0,11.502339,4462.06,---,43.68,---,NaN,---,---
4,2000-05,2851.0,11.502339,4371.14,---,44.08,---,NaN,---,---
...,...,...,...,...,...,...,...,...,...,...
310,2025-11,106740.0,28.298487,122834.00,408.4,88.84,5.5,197.9,0.71,0.3
311,2025-12,111262.0,28.303688,131322.55,433.9,90.04,5.25,198.0,1.33,0.05
312,2026-01,126904.0,28.303707,146169.80,---,90.90,5.25,NaN,2.38,0.0
313,2026-02,131630.0,28.303709,154370.40,---,90.75,5.25,NaN,2.86,0.0
314,2026-03,115395.0,28.309308,147395.00,---,92.82,5.25,NaN,3.12,0.0

In [295]:
df_master['Overall_CPI'] = df_master['Overall_CPI'].fillna("---")

In [296]:
df_master

,Date,Gold_Reservs_USD_mn,Gold_Volume_mn_troy_oz,Gold_Price[/10gm],Gold_CPI,USDINR,Repo_Rate,Overall_CPI,Inflation_YoY,Inflation_MoM
0,2000-01,2945.0,11.502339,4510.75,---,43.59,---,---,---,---
1,2000-02,3104.0,11.502339,4712.25,---,43.65,---,---,---,---
2,2000-03,2974.0,11.502339,4541.90,---,43.64,---,---,---,---
3,2000-04,2895.0,11.502339,4462.06,---,43.68,---,---,---,---
4,2000-05,2851.0,11.502339,4371.14,---,44.08,---,---,---,---
...,...,...,...,...,...,...,...,...,...,...
310,2025-11,106740.0,28.298487,122834.00,408.4,88.84,5.5,197.9,0.71,0.3
311,2025-12,111262.0,28.303688,131322.55,433.9,90.04,5.25,198.0,1.33,0.05
312,2026-01,126904.0,28.303707,146169.80,---,90.90,5.25,---,2.38,0.0
313,2026-02,131630.0,28.303709,154370.40,---,90.75,5.25,---,2.86,0.0
314,2026-03,115395.0,28.309308,147395.00,---,92.82,5.25,---,3.12,0.0

In [297]:
df_master.to_excel(
    "gold_master_dataset_with_cpi_and_inflation.xlsx",
    index=False
)